### ISSUE TITLE
trying to run a 32bit game on a 64bit installation

### ISSUE THREAD

**Issue by eduardonwa** [Winetricks/winetricks#1043]
saw this thread : https://github.com/Winetricks/winetricks/issues/599 because im trying to run a game (32bit) on a 64bit installation i was trying to instal lwinetricks dotnet40 mdx but it didnt let me. still cant install those i dont know why... thanks!!

**Comment by austin987** [comment]
@eduardonwa I'm not sure I understand what this issue is about? If you're asking about #599, this issue there was related to isolated prefixes (already fixed by https://github.com/Winetricks/winetricks/commit/6b449c6a5f7172899400262e2bed862fcc059e5d), but it sounds like you're asking about dotnet40 (which afaik works on win64, or at least, it's not longer blocked).

So...what's broken? What wine/winetricks version? Terminal output?
