### ISSUE TITLE
mdac27 download link dead

### ISSUE THREAD

**Issue by austin987** [Winetricks/winetricks#1070]
http://ftp.gunadarma.ac.id/pub/driver/itegno/USB%20Software/MDAC/MDAC_TYP.EXE is down, as is http://www.filewatcher.com/m/MDAC_TYP.EXE.5389224-0.html (mirror list).

**Comment by gverm** [comment]
@austin987 Opened PR #1072 for this.

**Comment by austin987** [comment]
Thanks!

**Comment by kakurasan** [comment]
I think we don't need to use archive.org because other URLs are still available (e.g. `http://up.voyager.pl/SupportFiles/MDAC/2.7%20SP1/EN/mdac_typ.exe`), besides, the old URL (`http://ftp.gunadarma.ac.id/pub/driver/itegno/USB%20Software/MDAC/MDAC_TYP.EXE`) still works for me (as of 11 Aug 2018).

Should we switch to the new URL?

**Comment by austin987** [comment]
@kakurasan I'm indifferent. archive.org isn't terribly reliable, but random FTP sites aren't either.

If you've got some reason to think the other site is more reliable (e.g., running in a loop shows it fails less), moving is fine. I just wanted winetricks-test to pass, so I could check other things ;).
