### ISSUE TITLE
Returned unexpanded string

### ISSUE THREAD

**Issue by greencopper** [Winetricks/winetricks#1082]
Running with the latest version (have installed using wget method).

```
wine cmd.exe /c echo '%ProgramFiles%' returned unexpanded string '%ProgramFiles%' ... this can be caused by a corrupt wineprefix, by an old wine, or by not owning ...
```

Also running latest wine-staging on Arch.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/768e5920f71cac91d1b6f04e0bd48d9d660d8814 adds better debugging info if this happens. Could you try with latest git and attach the output if you're still having issues.

**Comment by austin987** [comment]
Also, I just ran into this myself (I think because I CTRL+C'ed while running something, which presumably corrupted something in the registry).

The workaround I found was `wineboot -u`, which forces an update of your registry. Could you try that if you still have the problem? If it works I'll add that suggestion to the error message.

**Comment by dan-lind** [comment]
I ran into this problem today, can confirm that running `wineboot -u` solved the issue
