### ISSUE TITLE
Adobe Digital Editions 4.5 installer broken (4.5.8)

### ISSUE THREAD

**Issue by raspi** [Winetricks/winetricks#1092]
Current winetricks installer for Adobe Digital Editions 4.5 is broken. Installer says that it's already been started and you can retry it indefinitely. 

Downloading and installing older version installer works fine (tried with `4.5.0` installer from filehippo). Current version at Adobe download site is `4.5.8`.

Tried with 32 bit prefix.

**Comment by jasontibbitts** [comment]
I am having the same issue, running on Fedora 29 which has wine 3.20 and winetricks 20180603 (which I guess is a bit out of date).  I briefly looked through the commits since that release and didn't see anything related.  But I will see if I can try with a slightly older version.

The `adobe_diged` setup (instead of `adobe_diged4`) does still work well, though.

**Comment by Modelmat** [comment]
I have this issue too.

**Comment by austin987** [comment]
The problem is https://bugs.winehq.org/show_bug.cgi?id=46019. That bug lists a workaround (extract the installer rather than run it), which seems to work.

I added the workaround here:
https://github.com/Winetricks/winetricks/commit/0994d40427aaac20d5329222c4a880cd13a1778f

Looking upstream, looks like the app may have other issues that need to be fixed there (e.g., crashing when downloading a book or working with encrypted files).

**Comment by lord-ne** [comment]
Does anyone still have the installer file for Adobe Digital Editions 4.5.0? Can't seem to find anything online anymore
