### ISSUE TITLE
Check what already present and mark already installed Softwarein Winetricks

### ISSUE THREAD

**Issue by Mannshoch** [Winetricks/winetricks#1104]
It would be nice if Winetricks is able to perform some checks to see which functionality are already present, like mono vs. dotnet. It's sometimes difficult to get what software you have to install and what is already present.

Idea how to do that:
1. Run checks and test for software that is installed.
1. Preinstall a windows package manager, and work from there -> [OneGett](https://github.com/OneGet/oneget)

**Comment by austin987** [comment]
A) These are two separate things, they belong in different issues.
B) That said, I'm not sure what you're looking for. E.g., there's already winetricks_is_installed() which checks if things are installed. Mono can't be used by native .Net (which is mostly what's installing .Net), which is why it explicitly removes Mono first.
C) Re: OneGett, that depends on Powershell, which Wine doesn't have. In theory winetricks could install it, but afaik it doesn't work very well in Wine. Winetricks has support for nuget already.
