### ISSUE TITLE
7-Zip URL obsolete, needs to be updated

### ISSUE THREAD

**Issue by Beep6581** [Winetricks/winetricks#1142]
When winetricks b7e9e33738835c59e5cfb44e01261327d234e64e is run (tested using a clean installation of Linux Mint 19 XFCE 32-bit) and 7-Zip is not installed, winetricks tries to download `7z1602.exe` from SourceForge and fails, and then from archive.org and fails.

Valid links:
https://www.7-zip.org/a/7z1805.exe
https://www.7-zip.org/a/7z1604.exe
https://www.7-zip.org/a/7z920.exe

**Comment by ukos-git** [comment]
I just had a similar issue at the 7zip download step for `7z1602`. Can we re-open this issue. It is due to the mirror link referral on sourceforge.

I think it is a broadly unnoticed bug as `unzip` is installed on usual system.

```console
------------------------------------------------------
Cannot find unzip.  Using Windows 7-Zip instead. (You can avoid this by installing unzip, e.g. 'sudo apt-get install unzip' or 'sudo yum install unzip').
------------------------------------------------------
Executing w_do_call 7zip
Executing load_7zip 
Executing mkdir -p /home/igor/.cache/winetricks/7zip
Executing cd /home/igor/.cache/winetricks/7zip
Downloading https://downloads.sourceforge.net/sevenzip/7z1602.exe to /home/igor/.cache/winetricks/7zip
--2019-04-10 17:22:52--  https://downloads.sourceforge.net/sevenzip/7z1602.exe
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://sourceforge.net/projects/sevenzip/files/7-Zip/16.02/7z1602.exe/download?use_mirror=netcologne [following]
--2019-04-10 17:22:52--  https://sourceforge.net/projects/sevenzip/files/7-Zip/16.02/7z1602.exe/download?use_mirror=netcologne
Resolving sourceforge.net (sourceforge.net)... 216.105.38.13
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 232665 (227K) [text/html]
Saving to: '7z1602.exe'

7z1602.exe                 100%[=====================================>] 227.21K   411KB/s    in 0.6s    

2019-04-10 17:22:54 (411 KB/s) - '7z1602.exe' saved [232665/232665]
```

Problem in my case was the link that is passed to wget.

`https://sourceforge.net/projects/sevenzip/files/7-Zip/16.02/7z1602.exe/download?use_mirror=netcologne`.

The automatically added mirror is not resolved properly and downloads a file of <200K. Probably some website content.

If I use manual wget without the mirror suffix like so:

```bash
 wget https://sourceforge.net/projects/sevenzip/files/7-Zip/16.02/7z1602.exe
```

I get the proper file with a file size of 1.1M. Moving that over to the winetricks cache installs 7zip without problems.
