### ISSUE TITLE
Verb for KB2468871

### ISSUE THREAD

**Issue by DarkShadow44** [Winetricks/winetricks#1151]
Can we get a verb for KB2468871? You can try to install, but it's blocked by M$. But either this update or a fixed version of dotnet40 is needed for some programs to run.

See https://github.com/mohamedemam223/winetricks/issues/274 for an old bugreport with workaround.

Wine bug is https://bugs.winehq.org/show_bug.cgi?id=46249

**Comment by austin987** [comment]
So I tried the instructions from https://github.com/mohamedemam223/winetricks/issues/274, and got two msp's (sha256sums are):
547c766208346e954bf066cc2921a2210541bc06e611b081da3047b83cfe49b0  32/NDP40-KB2468871.msp
76d94002e43dc091cedaa1e026ba6baeb4251847a940772f015ca351016234f3  64/NDP40-KB2468871.msp

I added those to dotnet40, then tried the app from https://bugs.winehq.org/show_bug.cgi?id=46249. It complained to me in Cyrillic that I needed to install something from the redist folder. Turns out, they have a v2 from somewhere:
b1b53c3953377b111fe394dd57592d342cfc8a3261a5575253b211c1c2e48ff8  Redist/NDP40-KB2468871-v2-x64.exe
8822672fc864544e0766c80b635973bd9459d719b1af75f51483ff36cfb26f03  Redist/NDP40-KB2468871-v2-x86.exe

I'm not sure where those come from, but if we're going to install the hotfix, we probably want that version.

If you want to test, commit is here:
https://github.com/austin987/winetricks/commit/a383cf85b12524dab0ef3f5eb196dc4d822c5837

**Comment by DarkShadow44** [comment]
For some strange reason I get the following error from 7z:                                                  
```
Executing 7z x /home/fabian/.cache/winetricks/dotnet40/NDP40-KB2468871-v2-x64.exe NDP40-KB2468871.msp -o/home/fabian/.wine/dosdevices/c:/windows/temp/_dotnet40

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,12 CPUs Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz (206D7),ASM,AES-NI)

Scanning the drive for archives:
                                                  
ERROR: No more files
/home/fabian/.cache/winetricks/dotnet40/NDP40-KB2468871-v2-x64.exe NDP40-KB2468871.msp
```
It extracts just fine when manually running the command though...

**Comment by austin987** [comment]
@DarkShadow44 it was bad quoting, I've pushed a fix, could you retry please?

**Comment by DarkShadow44** [comment]
Fails for me: https://pastebin.com/nxrGFv2a

**Comment by austin987** [comment]
What wine version is that? I just tested in
wine-4.0
wine-4.14
wine-4.17-126-g15bf3eee2c

with 32-bit prefixes, installs fine.

**Comment by DarkShadow44** [comment]
I'm using Arch Linux Wine 4.17.
`WINEARCH=win32 ./winetricks.txt -q dotnet40`

Same error: https://pastebin.com/3YKa1ydR

**Comment by austin987** [comment]
Please retest with 5.0-rc* (which fixes https://bugs.winehq.org/show_bug.cgi?id=48277).

I suspect you are building with mingw (whereas I wasn't), which had its own (now fixed) issue.

**Comment by DarkShadow44** [comment]
Might be, it works with 4.21 already, and it does work with latest wine. Thanks.

**Comment by qwertychouskie** [comment]
Can this be closed now?

**Comment by austin987** [comment]
I think so, thanks for the reminder @qwertychouskie
