### ISSUE TITLE
New verb for FAudio (with ffmpeg support)

### ISSUE THREAD

**Issue by tgurr** [Winetricks/winetricks#1162]
https://github.com/Kron4ek/FAudio-Builds is offering pre-built FAudio builds with FFmpeg support for WMA playback compiled in. Would be nice to have this or any alternative as a verb to make use of the FAudio improvements required for some games to work without major sound issues.

**Comment by austin987** [comment]
@aeikum any thoughts?

**Comment by aeikum** [comment]
I think it's using the cpp/ stuff from FAudio instead of the COM support in Wine itself, which is more correct. So this may introduce crashes. But if users find it useful, I think it's fine to do something like this.

FWIW I'm planning to merge the FAudio work upstream ASAP after the 4.0 release. This may still be useful for users on older Wine releases.

**Comment by Gcenx** [comment]
It would be useful for same problematic games

**Comment by austin987** [comment]
Made a PR, please test it if you can.

**Comment by austin987** [comment]
Fixed by 6843ab3

**Comment by lemonzest79** [comment]
Just noticed this is pulling a version from 17th of Jan 2019, the latest is 19.03 released 1st March 2019, noticed this when I did a fresh install of a new prefix earlier, could this be fixed please?

**Comment by austin987** [comment]
Please open an issue for that, thanks.
