### ISSUE TITLE
d3dcompiler_43 verb is not shown in zenity GUI

### ISSUE THREAD

**Issue by tannisroot** [Winetricks/winetricks#1186]
Despite that such verb exists and works, it is not shown in the GUI (only d3dcompiler_47 one is):
![image](https://user-images.githubusercontent.com/10602045/54077055-521a7680-42c4-11e9-86e2-a2a4718a0f17.png)
Is this a bug or it's intentional?

**Comment by austin987** [comment]
Looks like it's because of this:
    `wine_showstoppers="24013"   # list a showstopper to hide this from average users for now`
see https://github.com/Winetricks/winetricks/blob/master/src/winetricks#L5989

which is https://bugs.winehq.org/show_bug.cgi?id=24013

So, intentional, I guess. Though IMHO it should either show it in both the CLI and GUI, or neither, particularly since this is the only dll it affects. I'm gonna think on it for a bit, but I'll likely change it (or close this).

**Comment by tannisroot** [comment]
Huh, that's weird. I use that task all the time with dgvoodoo2 and it works just fine...

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/f13b34f4a2f5ca59bbf0fe54eab434f65de04600
