### ISSUE TITLE
vcrun2017 verb uses older Visual C++ Redistributable version

### ISSUE THREAD

**Issue by Faalagorn** [Winetricks/winetricks#1190]
vcrun2017 verb uses older Visual C++ Redistributable version: running `exiftool` on versions downloaded from the script (and https://go.microsoft.com/fwlink/?LinkId=746571 and https://go.microsoft.com/fwlink/?LinkId=746572) reveal `14.11.25325.0`.

The most recent version is currently available from https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads (https://aka.ms/vs/15/release/vc_redist.x86.exe and https://aka.ms/vs/15/release/vc_redist.x64.exe) where running `exiftool` reveals `14.16.27027.1`.

I don't know if there's a changelog for the updates in between the versions Microsoft did (and running `exiftool` on `vc_redist.x64.exe` used from [Steamworks Common Redistributables](https://steamdb.info/depot/228987/) shows even older version at `14.10.25008.0` so it may not matter much), but it seems to be the latest version [according to Wikipedia](https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering). I'm not sure if the changes are meaningful enough to allow to download different VCrun versions (are they all even downloadable from MS servers anymore?) and I *assume* the latest version should generally be better (slight bugfixes, optimizations, whatever), but of course I may be wrong here or ultimately it may not matter other than the version number.

I guess I can write a PR for this if needed, but I wanted to post it as an issue at first.

**Comment by austin987** [comment]
In general I don't go looking for updates and and adding them. If there's a big or it fixes an application, then I'll revisit, of course.

There's technically a risk of regression, but I'm not very worried about it.

In short, if you really care send a PR. But I'm not going to update it myself unless it fixes an app.

**Comment by truboxl** [comment]
Oh great, Microsoft changed the version number again, 14.20.27508 and calls it Visual C++ 2015-2019

The ["The latest supported Visual C++ downloads"](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) also changed to include the so called "Visual C++ 2019" and removes all links to Visual C++ 2015 and Visual C++ 2017 though they still work for now.

Note: it uses the link https://aka.ms/vs/16/release/vc_redist.x64.exe
instead of https://aka.ms/vs/15/release/vc_redist.x64.exe
so the script is unaffected for now

My point here is that moving forward, if Microsoft changed the version number again using the same link, the script have to be updated over and over again (with new threads like this) to match checksum and its tedious.

Making another verb like vcrun2019 which supersedes vcrun2015 and vcrun2017 does not make anything better.

**Comment by austin987** [comment]
So.. what exactly are you proposing?

**Comment by Faalagorn** [comment]
Isn't it that everything that uses 2015 and above should also work with with 2019? I know winetricks currently have separate verb for vcrun2015 and vcrun2017, but are there any software that specifically need 2015 to run (wouldn't surprise me though)?
