### ISSUE TITLE
dotnet452 and dotnet40 conflict

### ISSUE THREAD

**Issue by sebi2306** [Winetricks/winetricks#1218]
It makes absolutely no sense for dotnet40 to conflict with dotnet452 when installing dotnet452 installs dotnet40 if it's not already there.
Basically, if you don't have dotnet40 installed `winetricks dotnet452` installs it. 
> w_call dotnet40 
> 

And if you already have dotnet40 installed, when you call `winetricks dotnet452`, you get a conflict error.

![nani](https://user-images.githubusercontent.com/6190216/56424516-405fc200-62b9-11e9-9701-58adecbd3376.png)

**Comment by sebi2306** [comment]
It makes no sense and I feel like `--force` shouldn't be required in this case.

**Comment by sebi2306** [comment]
Can anyone take a look at this basic common sense issue?

**Comment by austin987** [comment]
If it's simple, you could've sent a PR.

In any event, this was required some time ago. It was fixed in newer wine (sometime before wine-2.0), then in winetricks by https://github.com/Winetricks/winetricks/commit/ddf5c7c059ebc9b78031584cb82332e091c52d28.

I'd like to audit the other conflicts rather than fix them piecemeal. Since this isn't my day job and my free time is limited, it may take some time.

**Comment by austin987** [comment]
This should be fixed by https://github.com/Winetricks/winetricks/commit/c38a69a18b90db00e5e369388c427cd4792f044a (along with other combinations that now work in 4.0).
