### ISSUE TITLE
dsound failing to install

### ISSUE THREAD

**Issue by masternetra** [Winetricks/winetricks#1225]
Tryed to install Directmusic and while it was trying to install dsound it failed. Not the first time this has been the case for me on other distros.

Currents Distro: Zorin OS 15 (64bit)(Has occurred on Kubuntu 19.04, Linux Mint 18, and some others).
Wine Version: 4.7
Using a 32bit Prefix

Here is the bit from terminal

```
/home/mrkitsune67/.wine/dosdevices/c:/windows/temp/_dsound/dxnt.cab: WARNING; possible 5960 extra bytes at end of file.
Using native override for following DLLs: dsound
Executing wine regedit C:\windows\Temp\_dsound\override-dll.reg
Executing wine regsvr32 dsound.dll
regsvr32: 'DllRegisterServer' not implemented in DLL 'dsound.dll'
------------------------------------------------------
Note: command wine regsvr32 dsound.dll returned status 4. Aborting.
------------------------------------------------------
Gtk-Message: 19:03:15.680: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by dsheroh** [comment]
I'm seeing similar results trying to install dinput8.  My regsvr32 exit status id 5, so it's not the exact same final issue, but I'm getting the same cabextract warning from dxnt.cab, which makes me suspect the core issue may be something to do with directx_feb2010_redist.exe.  I've already looked at issue 1172 and, based on that, updated my cabextract to Debian's unstable version (1.9-2), but that has not resolved the problem.

~$ WINEPREFIX=~/.wine-tequila WINEARCH=win32 winetricks dinput8
Using winetricks 20190310-next - sha256sum: 3dfa60162c59ba8c3f2ea49a54b0fcb056f12ee1a8f012a8b62c66646bef73f3 with wine-4.0 and WINEARCH=win32
Executing w_do_call dinput8
Executing load_dinput8 
Executing cabextract -q -d /home/dsheroh/.wine-tequila/dosdevices/c:/windows/temp/_dinput8 -L -F dxnt.cab /home/dsheroh/.cache/winetricks/directx9/directx_feb2010_redist.exe
Executing cabextract -q -d /home/dsheroh/.wine-tequila/dosdevices/c:/windows/system32 -L -F dinput8.dll /home/dsheroh/.wine-tequila/dosdevices/c:/windows/temp/_dinput8/dxnt.cab
/home/dsheroh/.wine-tequila/dosdevices/c:/windows/temp/_dinput8/dxnt.cab: WARNING; possible 5960 extra bytes at end of file.
Using native override for following DLLs: dinput8
Executing wine regedit C:\windows\Temp\_dinput8\override-dll.reg
Executing wine regsvr32 dinput8
regsvr32: Failed to register DLL 'dinput8'
------------------------------------------------------
Note: command wine regsvr32 dinput8 returned status 5. Aborting.
------------------------------------------------------

(I'm adding this as a comment on the existing issue because, as I said, I suspect both of our problems are caused by the same underlying issue.  If you'd prefer that I file a separate issue, or if you think that it's not actually related, just let me know and I'll open a new report for it.)

**Comment by DarkShadow44** [comment]
Both cases are most likely the same issue, and regression by commit caa28d1af97ddd3d7b3e76ca7f51fb85fe1ce7eb.

Problem seems to be that the native dlls don't implement DllRegisterServer, they can't be registered. Some windows dlls just seem to have preexisting registration.

**Comment by austin987** [comment]
@zfigura

**Comment by iwasingh** [comment]
Same problem as @dsheroh 
```
Executing wine regsvr32 dinput8
0012:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0012:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0019:fixme:process:SetProcessShutdownParameters (00000380, 00000000): partial stub.
regsvr32: Failed to register DLL 'dinput8'
------------------------------------------------------
Note: command wine regsvr32 dinput8 returned status 5. Aborting.
------------------------------------------------------

```
@dsheroh, @DarkShadow44 are you able to solve it?
