### ISSUE TITLE
faudio instaler broken 404

### ISSUE THREAD

**Issue by dusanyu** [Winetricks/winetricks#1258]
404s out 

Executing cd /home/cmg/.cache/winetricks/faudio
Downloading https://web.archive.org/web/2000/https://github.com/Kron4ek/FAudio-Builds/releases/download/git-a756af4/faudio-git-a756af4.tar.xz to /home/cmg/.cache/winetricks/faudio
--2019-06-15 19:13:10--  https://web.archive.org/web/2000/https://github.com/Kron4ek/FAudio-Builds/releases/download/git-a756af4/faudio-git-a756af4.tar.xz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving web.archive.org (web.archive.org)... 207.241.233.214
Connecting to web.archive.org (web.archive.org)|207.241.233.214|:443... connected.
HTTP request sent, awaiting response... 404 NOT FOUND
2019-06-15 19:13:11 ERROR 404: NOT FOUND.

------------------------------------------------------
Downloading https://web.archive.org/web/2000/https://github.com/Kron4ek/FAudio-Builds/releases/download/git-a756af4/faudio-git-a756af4.tar.xz failed
------------------------------------------------------

**Comment by austin987** [comment]
That tarball was removed by faudio upstream. Latest winetricks (as of ce3e2413724d5b6505fc96c696356c899a4016b2) will get the latest release from an upstream URL, https://raw.githubusercontent.com/Kron4ek/FAudio-Builds/master/LATEST (19.06.07). However, since fuadio recently removed 32-bit, latest faudio is broken, see #1259.

The latest release in winetricks should work though, `faudio1904`.

**Comment by Taurolyon** [comment]
[Repo](https://github.com/Kron4ek/FAudio-Builds/) is now archived by owner and now read only. I assume this means it will not be updated.
