### ISSUE TITLE
w_detect_mingw doesn't work correctly

### ISSUE THREAD

**Issue by gverm** [Winetricks/winetricks#1461]
I get "Unable to detect wine dlls, please file an issue on Github"
I run wine from the 64bit build dir.
My exports are like this:
```
export WINE=/home/gverm/Desktop/64Bit/wine
export WINESERVER=/home/gverm/Desktop/64Bit/wineserver
```
I was running `WINEARCH=win32 ./winetricks.sh -q dotnet30sp1` when encountering this problem.
I tried both on a system where I build with mingw (macOS) and one where I build without (ArchLinux).

**Comment by austin987** [comment]
Not the problem here, but AFAIK a 64-bit build on its own doesn't work for much (unless this is OSX with codeweaver's clang fork)?

Anyway, I took an initial look when adding this, but couldn't find a good way to detect mingw with an in tree build. So I made it a FIXME until someone else cared :).

Do you have any ideas on how to detect mingw vs non-mingw here? Libraries don't get a `.dll` extension until `make install` is run. `file` can't tell the difference. The best idea I've had would be to detect if we're in a build tree (i.e., look for `configure` next to `wine` or something along those lines, then look at the build config (e.g., config.log or similar).

Other ideas very welcome.

**Comment by gverm** [comment]
> Not the problem here, but AFAIK a 64-bit build on its own doesn't work for much (unless this is OSX with codeweaver's clang fork)?

Note that this is not the case. It's a WOW64 build. I have a 64Bit and 32Bit folder. Built like done in here https://wiki.winehq.org/OpenSUSE#Building_Shared_WoW64

I'll think about some ideas.

**Comment by gverm** [comment]
@austin987 
>  Libraries don't get a .dll extension until make install is run.

Are you sure this is the case? I'm seeing:
```
(base) Gijss-MacBook-Pro:acledit gverm$ pwd
/Users/gverm/Desktop/Work/64Bit/dlls/acledit
(base) Gijss-MacBook-Pro:acledit gverm$ ls -la
total 152
drwxr-xr-x    5 gverm  staff    160 Jan  2 22:46 .
drwxr-xr-x  881 gverm  staff  28192 Dec 30 23:45 ..
-rw-r--r--    1 gverm  staff  14362 Jan  2 22:46 Makefile
-rwxr-xr-x    1 gverm  staff  50512 Jan  2 22:46 acledit.dll
-rw-r--r--    1 gverm  staff   7415 Dec 30 23:46 main.cross.o
```

**Comment by austin987** [comment]
@gverm I'm going from memory, which is never good :). Looking at the code, it seems .dll files were present.

Good catch; the Makefile.in idea won't work for out of tree builds (I generally build in tree so forgot about that). Is there a `Makefile` at the top of your build folder, next to the wine symlink? If so, it may be as simple as changing `Makefile.in` to `Makefile` in w_detect_mingw().

**Comment by gverm** [comment]
@austin987 That confuses me even more :p 
Since there is no Makefile.in next to the wine symlink, shouldn't in go inside the if-block instead of going inside the `elif test ! -d "$(dirname "${WINE}")"/../lib/wine; then` block?  Since `test -f "$(dirname "${WINE}")/Makefile.in"` returns 1?

**Comment by rmi1974** [comment]
Since wine-5.0-rc2 there is another (reliable) way that only needs to check one of the core dlls in the prefix. Winebuild adds a distinct PE file signature for PE builtins:

https://source.winehq.org/git/wine.git/commitdiff/9dc348a071fc626f85c3d3d7b40425712bde1e2c

Example check using 'winedump' (just to illustrate):

```console
$ winedump $(winepath -u "c:\\windows\\system32\\kernelbase.dll" 2>/dev/null) | grep "Wine builtin DLL"
*** This is a Wine builtin DLL ***
```

In case of a non-PE dll

```console
$ winedump $(winepath -u "c:\\windows\\system32\\dxgi.dll" 2>/dev/null) | grep "Wine builtin DLL"

$ winedump $(winepath -u "c:\\windows\\system32\\dxgi.dll" 2>/dev/null)
Contents of /home/focht/.wine/dosdevices/c:/windows/system32/dxgi.dll: 2472 bytes

*** This is a Wine fake DLL ***
...
```

A more elaborate version using 'grep' only:

```console
$ grep -obUaP "Wine builtin DLL" $(winepath -u "c:\\windows\\system32\\kernelbase.dll" 2>/dev/null)
64:Wine builtin DLL
```

The byte-offset output of match is useful since this is **lfanew = 0x40 + sizeof(fakedll_signature)**. Any other match would be a false positive.

But again, this would only work since wine-5.0-rc2.

Regards

**Comment by austin987** [comment]
Thanks. -P is a GNUism, but isn't needed anyway since there's no regex.

Testing with wine-devel-i386_5.0~rc4~eoan_i386.deb, it seems to work. I did find one false positive, as you suggested:
```
bash-5.0$ grep -obUa "Wine builtin DLL" *.dll | grep -v 64:
setupapi.dll:285172:Wine builtin DLL
```

(I won't be able to really test/fix/commit for a couple weeks, fyi). If someone wants to beat me to it, feel free. My thought is to check the wine version to make sure it's 5.0+ (and not rc1), and if so, use the grep method (since winedump may not be installed). If it's < 5.0-rc2, fall back to the current method). Also put a FIXME that we should rip it out when wine-6.0 comes out.

**Comment by Gcenx** [comment]
Checking for the wine header is no longer viable since Wine-5.1 now adds this header to PE files

**Comment by austin987** [comment]
@rmi1974 this seems to work for wine-4.11+:
https://github.com/austin987/winetricks/tree/mingw2

(I only tested 32-bit builds, though)

**Comment by rmi1974** [comment]
Well, look fine as proposed ;-)
I've made some statistics myself to see the progress per Wine release.
 
https://gist.github.com/rmi1974/f554b00609cdb0cdc32724d47a163fd2

This is for all binaries in Wow64 prefix from Wine 5.6:

PE -> 1609
fake -> 233

Doesn't look too bad .. but could be better. Various leftover fake executables are not that hard to convert, except core dlls and bigger components .. but I guess it's lower priority.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/d3be4c1533e976588125cd9d4e1106985e582a9b
