### ISSUE TITLE
controller support is broken with dinput8 verb

### ISSUE THREAD

**Issue by zany130** [Winetricks/winetricks#1499]
I need to use the dinput 8 verb in trails in sky to get the voice over mod to work but this breaks controller support.

**Comment by zany130** [comment]
if i start the game with a blank prefix controller will work but voices will not and if i start it with a prefix with the dinput8  verb selected vocies work but controller does not

**Comment by austin987** [comment]
I'm not sure this is fixable; it's possible another native dll may help. I'm doubtful though, since dinput/dinput8 needs to interface with the host hardware (i.e. /dev/js0) and the native version has no awareness of osx/linux hardware, it's not surprising that it breaks joystick support.

Anyway, this needs more investigation to be sure, but I'm relatively certain this will end up as a WONTFIX.

**Comment by zany130** [comment]
for my particular situation I was able to fix it by going into the wine config and setting  the override to native, builtin this seems to allow both the controller and the games moded dinput 8 to work together

**Comment by Gcenx** [comment]
Instead of using the dinput8 verb try instead making a clean prefix, installing the mod and still setting “native, builtin” for the dinput8 it should work.

Usually these kind of mods provide basically fake dll files that load the original and inject additional features.

**Comment by zany130** [comment]
> Instead of using the dinput8 verb try instead making a clean prefix, installing the mod and still setting “native, builtin” for the dinput8 it should work.
> 
> Usually these kind of mods provide basically fake dll files that load the original and inject additional features.

yeah thats what i did and everything is working

**Comment by austin987** [comment]
Invalid then.
