### ISSUE TITLE
Please provider vcrun2019 

### ISSUE THREAD

**Issue by gingters** [Winetricks/winetricks#1510]
Please also provide the 2019 Visual C++ runtime (vcrun2019).

Downloads:
The x86 version is here: https://aka.ms/vs/16/release/vc_redist.x86.exe
The x64 version is here: https://aka.ms/vs/16/release/vc_redist.x64.exe

The individual dll's contained in the downloads are listed here in the Docs: https://docs.microsoft.com/en-us/visualstudio/releases/2019/redistribution#-list-of-utilities-for-visual-studio-2019

Additional Info:
Based on the download page (https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads), the 2019 Visual C++ Runtime libraries _replace_ the existing 2015 and 2017 one, and this is deemed the single runtime for all three versions.

So, this change could additionally: Remove the conflict between vcrun2017 and 2015 and perhaps even replace the actual files for 2015 and 2017, so that vcrun2015, 2017 and 2019 all install the latest version of the combined runtime.

However, just providing the 2019 installation would be awesome enough for now.

**Comment by austin987** [comment]
It's already there:
https://github.com/Winetricks/winetricks/commit/94edaddc039c205a98c2a620399a741c7a70ce02
with a recent shasum update:
https://github.com/Winetricks/winetricks/commit/5f7b258fc8b644e00f779f65f8c69af8829a5fe1

note that that's not in the current release, which is why you're probably not seeing it. You can use --self-update to get the latest, or wait for the next release (imminent, see #1505).

**Comment by gingters** [comment]
Awesome. Thanks! The --self-update did the trick!
