### ISSUE TITLE
Do builtin and native dll's not coexist, becaues builtin dll's are deleted by winetricks?

### ISSUE THREAD

**Issue by Golddouble** [Winetricks/winetricks#1563]
I have added "d3dxof.dll" with winetricks to my winetricks prefix. But it seems, that it has overritten the builtin d3dxof.dll.
So does this mean, I can not set d3dxof.dll to "native, builtin" in winecfg, because builtin does no longer exist now?

I did the following:
I looked after d3dxof.dll in my winetricks prefix. It had 3.4 kb. I guess this was the builtin "d3dxof.dll" from wine.
Then I ainstalled with winetricks d3dxof.dll. It seems to be 49kb.
Now in my prefix the builtin dll was deleted and replaced through the native.
![winetricks native dll, windows32](https://user-images.githubusercontent.com/13977359/84662039-8810c680-af1b-11ea-8934-cec02826b039.png)

But in winecgf I want to set "d3dxof.dll" to "native, builtin". But I guess, I can't do this, because the builtin is deleted now.

Would appreciate some clarification. Thank you.

--------------------------------------------
Additional question: What is "d3dxof.dll.so" ?

**Comment by austin987** [comment]
This is really a wine question, not a winetricks one. The Wine FAQ may be helpful:
https://wiki.winehq.org/FAQ

It's hard to give a clear answer here, since it's A) complicated and B) dependent on upstream wine version, and C) is ongoing further changes upstream.

The .dll in the WINEPREFIX is a 'fake' dll. It doesn't contain the actual implementation, just enough to fake it out for most programs. That's not enough for all DRM schemes, so wine is moving to using mingw to build _real_ .dll files instead. That work is ongoing, and not all DLLs have migrated.

To answer your question, you should still be able to set `native, builtin`, as the builtin implementation is actually in the .dll.so file (in /usr/lib, or similar). If your application uses more invasive DRM though, that may not work and you'd need to make a new prefix (potentially wineboot -i or similar may work, but I don't know that for sure).
