### ISSUE TITLE
Winetricks questions concerning DLLs

### ISSUE THREAD

**Issue by ubotdude** [Winetricks/winetricks#1580]
I'm sure I am not the only person that has asked these question but my searches have not found any answers that I felt were adequate. If there is please point me there.

Which is better or safer? Running winetricks like

Method 1:
`WINEPREFIX=~/wine/app/32bit/productname/.name-to-use winetricks`

Then selecting the DLLs to add.

OR

Method 2:
`sh winetricks corefonts`

Installing one DLL at a time.

The reason I ask it that my app was running fine (but not perfectly). I had installed comctl32, comctl32ocx, and comdlg32ocx using the first method. When I added dotnet48 it also loaded dotnet40. Everything still worked. BUT when I attempted to add vcrun2015 I start seeing error messages telling me that comctl32 is not installed. Yet the Winetricks GUI says otherwise.

It appears that I am going to have to redo my prefix from scratch.

So would the second method be better and safer? Or is there a certain order that DLLs need to be installed in?  I'm running Ubuntu 16.04 and my Wine and winetricks is up to date.

Thanks for any help or comments.

Buddy

**Comment by austin987** [comment]
It shouldn't make any difference between method 1 or method 2 when installing a dll (apps may be treated differently without using --no-isolate, but that doesn't apply to dlls).

Order shouldn't matter, in general, unless you're dealing with verbs that have conflicts. I.e., if you install vcrun2015, you can't then install vcrun2019, since they conflict with each other.

**Comment by ubotdude** [comment]
Thanks @austin987 

I have been really careful how I install the DLLs especially the vcrun.  I'll poke around some more this weekend.

Buddy
