### ISSUE TITLE
'%ProgramFiles%' returned empty string

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Winetricks/winetricks#163]
```
I am receiving this error message when I try to install Visual Basic 6 runtimes

winetricks vb6run 
------------------------------------------------------ 
wine cmd.exe /c echo '%ProgramFiles%' returned empty string


I am using Wine 1.3.35 on a MacProBook 2 Ghz Intel Core i7 running OSX 10.7.2 
(Lion)
WINETRICKS_VERSION=20111115



```

Original issue reported on code.google.com by `DadsAn...@gmail.com` on 14 Jan 2012 at 6:59

**Comment by GNUGradyn** [comment]
Still getting this on ubuntu 16.10

**Comment by austin987** [comment]
Please open a new issue, and include the complete terminal output,
preferably as an attachment.

Also include wine/winetricks version.

**Comment by tomasjura** [comment]
`WINE=wine-development winetricks vb6run` did the trick. The problem is when WINEPREFIX is installed with one wine version (wine-development) using winecfg and another wine version (stable) under winetricks tries to get a variable.

**Comment by austin987** [comment]
Are you trying to use two wine versions on the same prefix at the same time?

**Comment by tomasjura** [comment]
Not the same time in the sense: two different wine server runs above one WINEPREFIX in **one** moment. The exact scenario is: 1) use wine-unstable in winecfg to initialize WINEPREFIX and terminate it and then 2) run wine (stable) with winetricks. The exact versions used in experiment were unstable: 2.12 and stable  1.8.7.

**Comment by austin987** [comment]
If wineserver hadn't terminated from the first command, the second would fail, and that's expected (user error).

Wine/winetricks don't care if you switch versions that a prefix uses, as long as its not running at the same time.

**Comment by jre-wine** [comment]
> If wineserver hadn't terminated from the first command, the second would fail, and that's expected (user error).

The Debian packaging only detects different wineserver (SERVER_PROTOCOL_VERSION) again since wine 1.8.5-1 and wine-development 1.9.19-1.

**Comment by austin987** [comment]
@jre-wine, I'm not sure what you're getting at, could you explain? 1.8.5 and 1.9.19 have different protocol versions:
@@ -6153,6 +6365,6 @@
     struct terminate_job_reply terminate_job_reply;
 };
 
-#define SERVER_PROTOCOL_VERSION 490
+#define SERVER_PROTOCOL_VERSION 517
 
 #endif /* __WINE_WINE_SERVER_PROTOCOL_H */

so if wineserver from the original command was still running, that could be why it fails.

I think it's worth see if wineserver is active, i.e., trying:
$ WINE=wine-unstable wineboot && wineserver -w && WINE=stable winetricks win7

and see if that has the problem

**Comment by jre-wine** [comment]
@austin987 The Debian packaging had been broken for some time until this was fixed in the mentioned versions (SERVER_PROTOCOL_VERSION was always 0 in the broken packages).  But after rereading the latest comments by @tomasjura the used versions should have been fixed ones, and the behavior should have been as you describe.

I guess I got confused a bit by the long buglog, and the mention of wine-unstable: wine-unstable has been replaced in Debian by wine-development several years ago. I guess that was a typo by @tomasjura since he used wine-development in his previous post.

**Comment by tomasjura** [comment]
@austin987 you were correct, it was an attempt to run different versions of wine at the same time. I inserted a pgrep command between the winecfg and winetricks calls and it clearly proved your hypotesis. The wine server is running couple seconds after a wine program (winecfg) finishes. I added a simple wait loop between wine calls and if the first wine really terminates, the second wine (winetricks) provides '%ProgramFiles%' without any errors. And winetricks also shows a message about updating the $WINEPREFIX.

@jre-wine I appologize for confusion with the wine-unstable. The wine-unstable name in Debian was used so long.

**Comment by austin987** [comment]
@tomasjura cool. FYI, you can use 'wineserver -w' to wait for wineserver to exit, instead of sleeping/looping.

**Comment by kenorb** [comment]
Related: https://bugs.winehq.org/show_bug.cgi?id=44575

**Comment by greencopper** [comment]
Same issue on Arch:

```
env WINEPREFIX=$HOME/wine-games/mass.effect.andromeda/ /usr/bin/winetricks

wine cmd.exe /c echo '%ProgramFiles%' returned unexpanded string '%ProgramFiles%' ... this can be caused by a corrupt wineprefix, by an old wine, or by not owning /home/foo/wine-games/mass.effect.andromeda/

winetricks --version
20180603 - sha256sum: cad4e699f55c297afe5b177d68dccf1ef54e9dd23518a6f6343caa0ab7636615
```

**Comment by kimpossible6** [comment]
I had the same issue:

warning: taskset/cpuset not available on your platform!
------------------------------------------------------
wine cmd.exe /c echo '%ProgramFiles%' returned unexpanded string '%SystemDrive%\Program Files (x86)' ... this can be caused by a corrupt wineprefix, by an old wine, or by not owning.....

Solved by typing:

rm -r ~/.wine
brew reinstall wine

**Comment by bferguson3** [comment]
Final post by kimpossible6 fixed it for me. (Thanks!)
I think the actual folder existing when running winetricks is causing the problem. Before I was cleaning the folder; using rm -r ~./wine might have done the trick.

**Comment by rkernegger** [comment]
> `WINE=wine-development winetricks vb6run` did the trick. The problem is when WINEPREFIX is installed with one wine version (wine-development) using winecfg and another wine version (stable) under winetricks tries to get a variable.

> `WINE=wine-development` worked for me too, thanks!

**Comment by greencopper** [comment]
I am sorry, but this is ludicrous! None of the above "solutions" is a solution!

Simply deleting ".wine" or whatever directory you have wine installed will work, but that's because you're removing everything. If you already have something installed, like applications or games, you cannot simply remove the wine directory.

Also updating DXVK currently relies on this working in Winetricks.

This problem has persisted since 2015. Can we please remove the thing from Winetricks where it looks for the "unexpanded string".

Just leave the string alone!

**Comment by greencopper** [comment]
A relatively simple hack is to delete the Wine installation in the relevant directory without actually deleting any of the installed applications. This can be done running the following commands (preferably set in a script).

```
rm -rf $WINEDIR/dosdevices
rm $WINEDIR/.update-timestamp
rm $WINEDIR/system.reg
rm $WINEDIR/user.reg
rm $WINEDIR/userdef.reg
rm $WINEDIR/winetricks.log
rm -rf $WINEDIR/drive_c/windows
```

Where "WINEDIR" is the relevant Wine directory.

If you're facing the above bug (still persisting since 2015) because you're trying to update DXVK, then removing the above stuff will also work.

**Comment by greencopper** [comment]
Also please reopen this as it is **not** resolved.

**Comment by austin987** [comment]
Does `wineserver -k` help?

**Comment by greencopper** [comment]
No.

**Comment by qwertychouskie** [comment]
Also try `wineboot -u`

**Comment by greencopper** [comment]
I am setting the WINEPREFIX manually for each and every directory with a wine installation so wineboot wont help.

**Comment by greencopper** [comment]
Remove the code from line 4954 to line 4959 in src/winetricks and the problem is solved. Forcing the creation of the wineprefix is wrong. The user needs to set this right in the first place.
