### ISSUE TITLE
warning: You are using a 64-bit WINEPREFIX

### ISSUE THREAD

**Issue by DocMAX** [Winetricks/winetricks#1730]
is there a way to disable this warning? nowadays 64bit gets more and more standard.

**Comment by austin987** [comment]
There's not.

While it is more common/standard, a lot of verbs only install 32-bit dlls (and a lot of things don't work on 64-bit) so I think the warning is justified.

**Comment by phibbs7** [comment]
Installing verb dotnet472 in a 64bit prefix requires clearing 18 of such warnings before the first installer dialog appears. I'd agree that such nagging is excessive.

If anything such numerous warnings just encourages users to either not bother with winetricks at all, or to edit the script to disable the warnings. It also gives users a poor impression of winetricks and wine in general because most consumer applications are 64bit nowadays. The tools coming up and declaring that 64bit support is half-baked at best, and to not even bother reporting bugs against it just leaves a bad taste in people's mouths. Let alone the constant stream of error messages making the tool itself seem to be bugged when in fact it is working as intended.

If such nagging is actually needed, maybe winetricks' 64bit support should better indicate in the selection menu what verbs won't work or will have issues in a 64bit prefix instead of annoying the users constantly. If support really is so hopeless maybe winetricks should just refuse to run in a 64bit prefix, unless a known working verb is given on the command line. (E.g. Disable the selection GUI in 64bit prefixes.)

**Comment by TheKodeToad** [comment]
This is not a solution, but I forked this project to only display warnings in the terminal as a temporary workaround.

**Comment by github12101** [comment]
Installing "all fonts" position require to click is about 100 times, this is madness!!! This warning should be suppressed to only one per session.

**Comment by Chiitoo** [comment]
I think using the CLI is a rather painless "workaround" for things like "requiring about 100 clicks" (there's also '-q' or '--unattended' which makes things like 'dotnet' installs a lot more bearable).

Is the original comment here about these GUI clicks, or the warning in general (including the CLI)?

**Comment by github12101** [comment]
> I think using the CLI is a rather painless "workaround" for things like "requiring about 100 clicks" (there's also '-q' or '--unattended' which makes things like 'dotnet' installs a lot more bearable).
> 
> Is the original comment here about these GUI clicks, or the warning in general (including the CLI)?

How I supposed to know what command install "all fonts" package? I launch winetricks directly from Lutris.

**Comment by Chiitoo** [comment]
I have no idea how Lutris manages things, and I don't know if it would break something if you run Winetricks manually (I don't think it should, but can't really say anything for sure).

In CLI, you can do things like this:

``` bash
$ winetricks --help # Lists options and commands.
$ winetricks fonts list # Lists fonts you can install.
$ winetricks allfonts
```

Normally this will use the default Wine prefix though, which will be "$HOME/.wine", and Lutris and similar tools might use different paths so one would need to specify the path to the prefix by doing something like this for example:

``` bash
$ WINEPREFIX="/path/to/the/prefix" winetricks allfonts
```

You might want to look into Lutris documentation and/or their support channels before trying any of this though.

**Comment by github12101** [comment]
> I have no idea how Lutris manages things, and I don't know if it would break something if you run Winetricks manually (I don't think it should, but can't really say anything for sure).
> 
> In CLI, you can do things like this:
> 
> ```shell
> $ winetricks --help # Lists options and commands.
> $ winetricks fonts list # Lists fonts you can install.
> $ winetricks allfonts
> ```
> 
> Normally this will use the default Wine prefix though, which will be "$HOME/.wine", and Lutris and similar tools might use different paths so one would need to specify the path to the prefix by doing something like this for example:
> 
> ```shell
> $ WINEPREFIX="/path/to/the/prefix" winetricks allfonts
> ```
> 
> You might want to look into Lutris documentation and/or their support channels before trying any of this though.

Thanks for this workaround. But this issue is affecting every single package offered in winetricks, not just "allfonts", if it's installing multiple components, you will get multiple notifications. This is unnecessary. Please disable this notification, it's useless when you have to click it 10th, 50th times each time you install a package in winetricks.

**Comment by austin987** [comment]
> it completely doesn't matter what winetricks has to say about my Lutris game profile.

It does; as I stated in https://github.com/Winetricks/winetricks/issues/1730#issuecomment-812992851. Several verbs only install 32-bit dlls. Others are completely broken in 64-bit prefixes. Users often things are equivalent between 32/64bit prefixes, but that is absolutely not the case when it comes to winetricks.

**Comment by austin987** [comment]
This is a bit hacky, but given the strong sentiment, I've got a patch that addresses this:
https://github.com/austin987/winetricks/commit/01de762dfa656471cee0df3f6508b82a07de9117

Please test.

**Comment by h8rt3rmin8r** [comment]
> 

I entirely agree. I just suffered through like 100 error dialogues to get fonts installed. This is way over the top in my opinion.

**Comment by austin987** [comment]
There's a fix, and yet no one has tested  it in 4 months..

**Comment by phibbs7** [comment]
Sorry, the original notification email for the fix got lost in the spam filter.

The fix does work. Using all fonts on a fresh wine prefix as an example, the 64bit warning only pops up once. Even though multiple verbs are executed. (And even a reiteration of some fonts? Seems that some font verbs are executed twice because of being included by corefonts. Hard to tell given that there's no indication of what font is being worked on or how many are left to process. But that's for another bug to sort out.)

What may cause confusion for some users down the line is that the warning is suppressed indefinitely. (Current iteration looks for a file to be present in the prefix root, but doesn't clear it when winetricks exits.) If a user forgets that a profile is 64bit, the permanent dismissal may cause confusion later when a newer wine version comes out and the needed verbs change for a given program. It's nice to be able to dismiss the warning permanently, but maybe dismiss it per winetricks session / wine version by default. With the permanent option being select able as a CLI arg.

**Comment by Sommerwiesel** [comment]
Please devs can't you just give us a proper way to disable this horribly annoying warning?
It's an absolute nightmware to work with winetricks under a desktop gui.

**Comment by mikkorantalainen** [comment]
How about making winetricks smarter and not offering to install broken packages? This whole warning is not needed at all if winetricks wouldn't offer installing packages that do not work in 64 bit wineprefix.

If winetricks is then run with 64 bit prefix, it would show a warning *once* during the startup that some packages/verbs are missing because they do not work with 64 bit prefix.

**Comment by criptixo** [comment]
Devs please listen to the community and give us a an easy backed-in way to disable this annoying warning.

**Comment by austin987** [comment]
> Devs please listen to the community and give us a an easy backed-in way to disable this annoying warning.

See https://github.com/Winetricks/winetricks/commit/87f7cb8f69c204cc0a9191f6c0b71a67425ef65c.

**Comment by austin987** [comment]
> How about making winetricks smarter and not offering to install broken packages? This whole warning is not needed at all if winetricks wouldn't offer installing packages that do not work in 64 bit wineprefix.

It would be a non-significant amount of work. Volunteers welcome!

> If winetricks is then run with 64 bit prefix, it would show a warning _once_ during the startup that some packages/verbs are missing because they do not work with 64 bit prefix.

That's already the case (once per session), and it can be disabled by simply touching a file...

**Comment by smumriak** [comment]
> That's already the case (once per session), and it can be disabled by simply touching a file...

it does not work :) i can clearly see console message saying "blah blah found file disabling warning" and still posting it

**Comment by zpangwin** [comment]
### Proposal:

Change this

> This is a bit hacky, but given the strong sentiment, I've got a patch that addresses this: [austin987@01de762](https://github.com/austin987/winetricks/commit/01de762dfa656471cee0df3f6508b82a07de9117)
> 
> Please test.

specifically this section

    # 64-bit prefixes still have plenty of issues/a lot of verbs only install 32-bit libraries
    # Allow the user to disable that (globally, or per prefix).
    if test -f "${W_CACHE}/no_win64_warnings"; then
        echo "${W_CACHE}/no_win64_warnings exists, not issuing 64-bit prefix warning"
        _W_no_win64_warnings=1
    elif test -f "${WINEPREFIX}/no_win64_warnings"; then
        echo "${WINEPREFIX}/no_win64_warnings exists, not issuing 64-bit prefix warning"
        _W_no_win64_warnings=1
    elif test -f "${W_TMP_EARLY}/no_win64_warnings"; then
        echo "${W_TMP_EARLY}/no_win64_warnings exists, not issuing 64-bit prefix warning"
        _W_no_win64_warnings=1
    else
        _W_no_win64_warnings=0
    fi

To instead use wrap the IF/ELSE structure with a check for whether or not an environment variable was passed, e.g.:

    # 64-bit prefixes still have plenty of issues/a lot of verbs only install 32-bit libraries
    # Allow the user to disable that (globally, or per prefix).
    if test -z "${_W_no_win64_warnings}"; then
        if test -f "${W_CACHE}/no_win64_warnings"; then
            echo "${W_CACHE}/no_win64_warnings exists, not issuing 64-bit prefix warning"
            _W_no_win64_warnings=1
        elif test -f "${WINEPREFIX}/no_win64_warnings"; then
            echo "${WINEPREFIX}/no_win64_warnings exists, not issuing 64-bit prefix warning"
            _W_no_win64_warnings=1
        elif test -f "${W_TMP_EARLY}/no_win64_warnings"; then
            echo "${W_TMP_EARLY}/no_win64_warnings exists, not issuing 64-bit prefix warning"
            _W_no_win64_warnings=1
        else
            _W_no_win64_warnings=0
        fi
    fi

----

### Example usage:

    WINEPREFIX="/some/path/to/some/game" WINEARCH="win64" _W_no_win64_warnings=1 winetricks win10 corefonts mfc42 quartz faudio

----

### Advantages:

1. Allows users to *completely* suppress the message (including echo statement from touched file) if they *really* want to
2. Allows to set an environment variable for a terminal session but not forever (or alternately could use `.bashrc` or equivalent for all terminal sessions)
3. Reduced number of I/O hits checking for a file (I know it is an *extremely* minor I/O hit but it's still *technically* a plus)
4. This also allows a user to temporarily turn the warning back on if they have created the file but wish to restore the warning temporarily such as for a single debugging session.

----

not sure if there are strong feelings on this or not, hence the comment here as a proposal rather than simply submitting a PR

**Comment by melroy89** [comment]
Why not put this warning behind the same `-q` flag we already have?

**Comment by austin987** [comment]
> Why not put this warning behind the same `-q` flag we already have?

It already is.

**Comment by austin987** [comment]
> ### Advantages:
> 
>     1. Allows users to _completely_ suppress the message (including echo statement from touched file) if they _really_ want to
> 
>     2. Allows to set an environment variable for a terminal session but not forever (or alternately could use `.bashrc` or equivalent for all terminal sessions)
> 
>     3. Reduced number of I/O hits checking for a file (I know it is an _extremely_ minor I/O hit but it's still _technically_ a plus)
> 
>     4. This also allows a user to temporarily turn the warning back on if they have created the file but wish to restore the warning temporarily such as for a single debugging session.
> 
> 
> not sure if there are strong feelings on this or not, hence the comment here as a proposal rather than simply submitting a PR
> 
> If this is acceptable, then it would probably also be worthwhile to change the case on the variable / maybe rename it so as to follow normal environment variable conventions.
> 
> e.g. also run something like
> 
> ```
> sed -i 's/_W_no_win64_warnings/W_NO_WIN64_WARNINGS/g' ./src/winetricks
> ```

That seems reasonable, feel free to send a PR.
