### ISSUE TITLE
ie8 32bit: Since Wine 6.6, doesn't install

### ISSUE THREAD

**Issue by alessivs** [Winetricks/winetricks#1768]
Affected:

- Wine 6.6
- Wine 6.7
- Wine 6.8
- Wine 6.9
- Wine 6.10
- Wine 6.11
- Wine 6.12
- Winetricks master

Installed with:

```sh
WINEDLLOVERRIDES=winemenubuilder.exe=d WINEARCH=win32 WINEPREFIX=~/.local/share/wineprefixes/ie8 sh ~/src/winetricks/src/winetricks -q ie8 winxp
```

[Install log](https://gist.githubusercontent.com/alessivs/839d0c7e553e66560458b3e886954776/raw/7e4bf5b3b43aaf48ce42944fc2b799bdb4f8416a/ie8-wine-6.6-install.log)

Failed to install:

```
Executing cd /home/fm/.cache/winetricks/ie8
01b0:err:module:import_dll Library shlwapi.dll (which is needed by L"C:\\windows\\system32\\SHELL32.dll") not found
01b0:err:module:import_dll Library SHELL32.dll (which is needed by L"Y:\\ie8\\IE8-WindowsXP-x86-ENU.exe") not found
01b0:err:module:LdrInitializeThunk Importing dlls for L"Y:\\ie8\\IE8-WindowsXP-x86-ENU.exe" failed, status c0000135
Executing cd /home/fm/.local/share/wineprefixes/ie8/dosdevices/c:/windows/system32
------------------------------------------------------
warning: Working around wine bug 25648 -- Setting TabProcGrowth=0 to avoid hang
------------------------------------------------------
Executing wine regedit /S C:\windows\Temp\set-tabprocgrowth.reg
0360:err:module:import_dll Library shlwapi.dll (which is needed by L"C:\\windows\\system32\\shell32.dll") not found
0360:err:module:import_dll Library shell32.dll (which is needed by L"C:\\windows\\system32\\start.exe") not found
0360:err:module:LdrInitializeThunk Importing dlls for L"C:\\windows\\system32\\start.exe" failed, status c0000135
------------------------------------------------------
warning: Note: command wine regedit /S C:\windows\Temp\set-tabprocgrowth.reg returned status 53. Aborting.
------------------------------------------------------
```

## History

| Date                 | Summary         |
|----------------------|-----------------|
| 2021-07-04T20:24:43Z | Added Wine 6.12 |
| 2021-06-20T05:24:40Z | Added Wine 6.11 |
| 2021-06-13T15:30:27Z | Added Wine 6.10 |
| 2021-05-29T07:44:27Z | First report    |

**Comment by KokoseiJ** [comment]
Can confirm,
```
Executing mv /home/kokoseij/.wine32/dosdevices/c:/Program Files/Internet Explorer/iexplore.exe /home/kokoseij/.wine32/dosdevices/c:/Program Files/Internet Explorer/iexplore.exe.bak
Executing mv /home/kokoseij/.wine32/dosdevices/c:/windows/system32/browseui.dll /home/kokoseij/.wine32/dosdevices/c:/windows/system32/browseui.dll.bak
Executing mv /home/kokoseij/.wine32/dosdevices/c:/windows/system32/inseng.dll /home/kokoseij/.wine32/dosdevices/c:/windows/system32/inseng.dll.bak
Executing mv /home/kokoseij/.wine32/dosdevices/c:/windows/system32/itircl.dll /home/kokoseij/.wine32/dosdevices/c:/windows/system32/itircl.dll.bak
Executing mv /home/kokoseij/.wine32/dosdevices/c:/windows/system32/itss.dll /home/kokoseij/.wine32/dosdevices/c:/windows/system32/itss.dll.bak
Executing mv /home/kokoseij/.wine32/dosdevices/c:/windows/system32/jscript.dll /home/kokoseij/.wine32/dosdevices/c:/windows/system32/jscript.dll.bak
Executing mv /home/kokoseij/.wine32/dosdevices/c:/windows/system32/msctf.dll /home/kokoseij/.wine32/dosdevices/c:/windows/system32/msctf.dll.bak
Executing mv /home/kokoseij/.wine32/dosdevices/c:/windows/system32/mshtml.dll /home/kokoseij/.wine32/dosdevices/c:/windows/system32/mshtml.dll.bak
Executing mv /home/kokoseij/.wine32/dosdevices/c:/windows/system32/shdoclc.dll /home/kokoseij/.wine32/dosdevices/c:/windows/system32/shdoclc.dll.bak
Executing mv /home/kokoseij/.wine32/dosdevices/c:/windows/system32/shdocvw.dll /home/kokoseij/.wine32/dosdevices/c:/windows/system32/shdocvw.dll.bak
Executing mv /home/kokoseij/.wine32/dosdevices/c:/windows/system32/shlwapi.dll /home/kokoseij/.wine32/dosdevices/c:/windows/system32/shlwapi.dll.bak
Executing mv /home/kokoseij/.wine32/dosdevices/c:/windows/system32/urlmon.dll /home/kokoseij/.wine32/dosdevices/c:/windows/system32/urlmon.dll.bak
```
It renames various .dlls with `.bak` suffix, which includes `shwlapi.dll` that is needed by `shell32.dll`. causing even `start.exe` to not be able to run. This glitch not only doesn't allow users to install ie8, but also breaks the entire WINEPREFIX.

**Comment by hackomatic** [comment]
The following patch is supposed to fix the IE8 installation. What is does:
1. restore broken prefix by extracting DLLs (set to 'native' overrride) from the IE bundle
2. remove msctf from the removed DLLs list, otherwise IE8 installer won't do anything

--- winetricks	2021-06-28 17:23:47.299318602 +0300
+++ winetricks.new	2021-06-28 17:20:52.673918945 +0300
@@ -15264,16 +15264,6 @@
     # Bundled updspapi cannot work on Wine
     w_override_dlls builtin updspapi
 
-    # Remove the fake DLLs from the existing WINEPREFIX
-    if [ -f "${W_PROGRAMS_X86_UNIX}/Internet Explorer/iexplore.exe" ]; then
-        w_try mv "${W_PROGRAMS_X86_UNIX}/Internet Explorer/iexplore.exe" "${W_PROGRAMS_X86_UNIX}/Internet Explorer/iexplore.exe.bak"
-    fi
-
-    for dll in browseui inseng itircl itss jscript msctf mshtml shdoclc shdocvw shlwapi urlmon; do
-        test -f "${W_SYSTEM32_DLLS}"/${dll}.dll &&
-            w_try mv "${W_SYSTEM32_DLLS}"/${dll}.dll "${W_SYSTEM32_DLLS}"/${dll}.dll.bak
-    done
-
     # See https://bugs.winehq.org/show_bug.cgi?id=16013
     # Find instructions to create this file in dlls/wintrust/tests/crypt.c
     w_download https://github.com/Winetricks/winetricks/raw/master/files/winetest.cat 5d18ab44fc289100ccf4b51cf614cc2d36f7ca053e557e2ba973811293c97d38
@@ -15284,6 +15274,18 @@
 
     w_download https://download.microsoft.com/download/C/C/0/CC0BD555-33DD-411E-936B-73AC6F95AE11/IE8-WindowsXP-x86-ENU.exe 5a2c6c82774bfe99b175f50a05b05bcd1fac7e9d0e54db2534049209f50cd6ef
 
+    # Remove the fake DLLs from the existing WINEPREFIX
+    if [ -f "${W_PROGRAMS_X86_UNIX}/Internet Explorer/iexplore.exe" ]; then
+        w_try mv "${W_PROGRAMS_X86_UNIX}/Internet Explorer/iexplore.exe" "${W_PROGRAMS_X86_UNIX}/Internet Explorer/iexplore.exe.bak"
+    fi
+
+    # Replace the fake DLLs by copies from the bundle
+    for dll in browseui inseng itircl itss jscript mshtml shdoclc shdocvw shlwapi urlmon; do
+        test -f "${W_SYSTEM32_DLLS}"/${dll}.dll &&
+            w_try mv "${W_SYSTEM32_DLLS}"/${dll}.dll "${W_SYSTEM32_DLLS}"/${dll}.dll.bak &&
+            w_try_cabextract --directory="${W_SYSTEM32_DLLS}" "${W_CACHE}"/ie8/IE8-WindowsXP-x86-ENU.exe -F ${dll}.dll
+    done
+
     # KLUDGE: if / is writable (as on OS X?), having a Z: mapping to it
     # causes ie7 to put temporary directories on Z:\.
     # So hide it temporarily.  This is not very robust!

**Comment by hackomatic** [comment]
Looks like github tries to interpret .diff and displays broken contents, is there a way to attach it instead?

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/db85f885516d4bdce6d29e6317d2c515693aa0bc
