### ISSUE TITLE
[Request] Releases for Distribution Package Maintenance

### ISSUE THREAD

**Issue by gbschenkel** [Winetricks/winetricks#1889]
Hi @austin987,

I would like to ask you for release a few more constant Releases, for package maintenance on Distro, at least for Slackware, because for default Slackware don't use self-updates, or git clone, for build the packages, just compacted source code or a binary when the source is not available.

Is a bit weird `--version` always show the same version, with only sha256 changing only.
Maybe you could do a CI/CD to auto-release a version once a week or two, since you are always working, running [src/release.sh](https://github.com/Winetricks/winetricks/blob/master/src/release.sh) before tagging the Release.
This way you could help the distro have a updated version of your work.

Thank you for your attention.

**Comment by bobwya** [comment]
@austin987 is there any reason for all the random tags being added, and yet no official release since August 2021?

**Comment by austin987** [comment]
@bobwya TL;DR: PEBKAC. Release in-progress/soonish.

Testing things, and thought I was pushing to my fork (https://github.com/austin987/winetricks), but forgot that the script that actually interacts with the github api hardcodes the github project, rather than deriving it from the git remote :(. Which I unfortunately I didn't figure out until a few days ago (but was very confused at why some things weren't showing up on my fork..).

As an aside, I'm not sure if I need to to tweak my github settings, but I don't get notifications for tags/releases that I do, presumably since I initiated them (otherwise I probably would've realized my mistake much sooner ;)).

That said, I've got some time to work on this, so looking closer. I believe I have the upload issues worked out. There are a few wine regressions that I wanted to look at/open bugs for first, in particular:
https://bugs.winehq.org/show_bug.cgi?id=52743
https://bugs.winehq.org/show_bug.cgi?id=52772

**Comment by austin987** [comment]
@gbschenkel,

Apologies for a delayed release. Things have been hectic :), but yes, I should do more.

That said, I do not intend to set up autoreleases (in particular, for QA reasons and because releases are GPG signed, not something I'm putting on the cloud..).

I'll leave this open though until a proper release is made ;).

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/releases/tag/20220411
