### ISSUE TITLE
Installing a native override, reseting it and then trying to install again fails

### ISSUE THREAD

**Issue by shmerl** [Winetricks/winetricks#1896]
I tried doing this:

```
winetricks d3dcompiler_47
```

It installed the override fine.

Then I reverted it like this:

```
winetricks d3dcompiler_47=default
```
That worked as well:

```
Using default override for following DLLs: d3dcompiler_47
Executing wine regedit C:\windows\Temp\_default\override-dll.reg
Executing wine64 regedit C:\windows\Temp\_default\override-dll.reg
```

But then when I tried to do the native override the second time, it failed:

```
winetricks d3dcompiler_47
...
d3dcompiler_47 already installed, skipping
```

Am I missing something or I'm doing it wrong?

Version (from Debian testing):

```
winetricks --version
20210206 - sha256sum: 0f21da98811e0bfda16a7d6d6b8e860a9cedbd4e836c7dd9b02f068d3092ee2e
```

**Comment by austin987** [comment]
Hi @shmerl,

`winetricks d3dcompiler_47`

installs native d3dcompiler_47.dll, *and* overrides it to native

When you run:

`winetricks d3dcompiler_47=default`

It sets the override to default (i.e., builtin).

Re-running:

`winetricks d3dcompiler_47`

then tries to reinstall d3dcompiler_47, which gives an error, since it's already installed. You have two options:

1) Use: `winetricks d3dcompiler_47=native` to set to the dll back to native.

2) `winetricks --force d3dcompiler_47` to reinstall the dll, *and* set it to native.

(you could also run `winecfg` and change it manually there too ;)).

**Comment by shmerl** [comment]
Thanks.

Is there some command that installs the built-in dll into the prefix, essentially "uninstalling" the native one, i.e. not simply changing the override to built-in but also changing the dll?

**Comment by austin987** [comment]
There isn't.

If someone wants to submit a patch, I'd review it, but personally I don't think it's worth adding. Getting it right is non-trivial, particularly across all possibilities (32/64 bit prefixes, mingw/non-mingw, every dll option that winetricks supports).
