### ISSUE TITLE
Chinese fonts used is not ideal

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Winetricks/winetricks#199]
```
What steps will reproduce the problem?
1. rm -rf ~/.wine
2. winetricks cjkfonts
3. LANG=zh_CN.utf8 wine notepad

What is the expected output? What do you see instead?
The Chinese rendering is not very ideal. See the attachments below.

What version of the product are you using? On what operating system?
$ wine --version
wine-1.5.2

$ ./winetricks --version
20120308

$ uname --all
Linux debian 2.6.32-5-686 #1 SMP Mon Mar 26 05:20:33 UTC 2012 i686 GNU/Linux

Please provide any additional information below.
Bitmap Chinese fonts are widely used in Chinese version of Microsoft Windows at 
least in releases prior to (including) Windows XP.
```

Original issue reported on code.google.com by `damage3...@gmail.com` on 22 Apr 2012 at 6:24

**Comment by fracting** [comment]
I believe this one is fixed in latest winetricks.

CrossOver use AR PL UMing CN as replacement of SimSun font, while latest winetricks use Wen Quan Yi Micro Hei as replacement of SimSun, either of them has its own positive and negative, but at least Chinese font should display correctly now.

According to my test, winetricks 20150416 - sha1sum: 1254cbf24167bfa25e895f65c211416ffa853789 (and some earlier versions) already fix this issue, the winecfg GUI display Chinese correctly after `winetricks cjkfonst`

**Comment by austin987** [comment]
Great, thanks.
