### ISSUE TITLE
sha256sum for vc_redist.86.exe is failing

### ISSUE THREAD

**Issue by dbyy** [Winetricks/winetricks#1992]
Hi,
I downloaded the latest version of winetricks (20210206) to install sketchup2017 in wine v. 7.0.1 on Linux Mint v21 - Vanessa.
when executing the command "env WINEPREFIX=$HOME/.sketchup2017 winetricks vcrun2019 corefonts" it fails with the message 
"sha256sum mismatch".
The shasum of the downloaded file is "4c6c420cf4cbf2c9c9ed476e96580ae92a97b2822c21329a2e49e8439ac5ad30".
However this shasum is nowhere listed in the winetricks script.
I guess that's the reason why the download fails.

I tried to analyze 'winetricks' to find the location of the download in the script but it is very 'convoluted' and hard to find.
It also seems that the download started at 'aka.ms' but then it's get redirected to "download.visualstudio.microsoft.com'.

I'm wondering, am I missing a step in whole download process or is there somewhere a bug in the script.

Any help is much appreciated.

**Comment by dbyy** [comment]
no comment from anyone?

**Comment by austin987** [comment]
It's a known/fixed issue (in master). You have a couple options:
1) use '--update' to update winetricks to the latest master, which should avoid this
2) use '--force' to ignore the checksum check (microsoft made a new release at the same URL/filename, which is why this occurs).

It will be fixed by the next release (then broken again, whenever microsoft makes an in place upgrade again..).

**Comment by dbyy** [comment]
Thanks for the update.
