### ISSUE TITLE
Feature request : Add dotnet60

### ISSUE THREAD

**Issue by dginovker** [Winetricks/winetricks#1999]
https://dotnet.microsoft.com/en-us/download/dotnet/6.0

It's starting to get asked about online:
* https://www.reddit.com/r/winehq/comments/wq86f2/how_to_run_a_dotnet_6_app/
* https://www.reddit.com/r/linuxquestions/comments/xh1ysn/installing_net_60_in_wine/

Much love! :heart:

**Comment by begin-theadventure** [comment]
Also Desktop Runtime 6.

**Comment by austin987** [comment]
Can someone please try https://github.com/austin987/winetricks/commit/6d34077be372f6aba7cf22115b49b862428f658c (from https://github.com/austin987/winetricks/tree/issue-1999-dotnet6)? I didn't find any sample .net 6 applications that didn't require an account in a quick search.

**Comment by Saancreed** [comment]
I gave it a try with `winetricks -q dotnetdesktop6` and [ILSpy](https://github.com/icsharpcode/ILSpy/releases/tag/v8.0-preview3) (`ILSpy_binaries_8.0.0.7246-preview3.zip` package is not selfcontained and requires the runtime to be installed), seems to work okay-ish:

![image](https://user-images.githubusercontent.com/26201033/213597233-091b4511-1204-43f8-b265-df0ce151b5fd.png)

![image](https://user-images.githubusercontent.com/26201033/213597681-58e1feca-a595-4dcb-925b-e9ebfbdf46f0.png)

However, the verb installed both 32-bit and 64-bit runtimes in my 64-bit prefix which doesn't make sense as the former is pretty much useless if your system can run the latter.

**Comment by austin987** [comment]
> I gave it a try with `winetricks -q dotnetdesktop6` and [ILSpy](https://github.com/icsharpcode/ILSpy/releases/tag/v8.0-preview3) (`ILSpy_binaries_8.0.0.7246-preview3.zip` package is not selfcontained and requires the runtime to be installed), seems to work okay-ish:

Thanks!

> However, the verb installed both 32-bit and 64-bit runtimes in my 64-bit prefix which doesn't make sense as the former is pretty much useless if your system can run the latter.

Many applications still ship 32-bit components, we can't know in advance what a user expects. IMO it's not worth the extra complexity in the script/confusion for users to separate the two. If space if of extreme importance, a user can either automate their own install trivially, or uninstall 32-bit dotnet afterward.

**Comment by Saancreed** [comment]
> Many applications still ship 32-bit components

Maybe old .NET Framework applications used to do this, but I've seen quite a lot of .NET 6.0+ applications and all of them either did not care because they were fully CLR based with no native components, shipped both 64-bit and 32-bit native libraries, or (very rarely) required 64-bit runtime. Not a single one had a requirement of 32-bit runtime; nowadays this doesn't happen because virtually all the NuGet packages support both, and I guess that even if one was to find such an application, it would be distributed as a selfcontained package that doesn't need systemwide runtime to be installed (because that would also be quite a hurdle for Windows users as well).

> IMO it's not worth the extra complexity in the script/confusion for users to separate the two.

Fair enough, but on the other hand I'd just really like to know if any application that requires precisely 32-bit runtime actually exists.

**Comment by mercifulboss** [comment]
> 

How do I get the command `winetricks -q dotnetdesktop6` to work. I get an error `Unknown arg dotnetdesktop6`

**Comment by ultimatespirit** [comment]
I ran into this issue too, make sure your `winetricks` is up to date with `winetricks --self-update` (or whatever appropriate update mechanism for your system).

**Comment by mercifulboss** [comment]
> I ran into this issue too, make sure your `winetricks` is up to date with `winetricks --self-update` (or whatever appropriate update mechanism for your system).

Thank you. It worked
