### ISSUE TITLE
winetricks will silently fail if only wine64 executable is present

### ISSUE THREAD

**Issue by wojnilowicz** [Winetricks/winetricks#2052]
`sh winetricks` will show nothing, if wine is built from sources on an 64-bit only Linux distribution. Wine is made available by adding its executable path in the following way PATH="/path/to/wine/bin:$PATH". There is no **wine** executable, only **wine64**.

**Comment by ericoporto** [comment]
See #2040

**Comment by austin987** [comment]
#2040 is about the OSX packages (which have a peculiar setup), this is about a Linux build, compiled from source.

As far as I know, this not a supported configuration upstream. You should still get a GUI (if zenity/kdialog is available), or an error message if not and running from a terminal. Running here with a setup like that, I do get a GUI or the error message.

Without logs, I'm not sure what went wrong. But given that this is an unsupported configuration, it's not a high priority. Particularly since detecting this case (while not breaking supported configurations) will complicate the code further..

**Comment by wojnilowicz** [comment]
Ok, I didn't know that it isn't supported upstream. I do not see on their website what's supported upstream though.
No log was visible to me, and I did not dig deeper. All I know is that creating a wine link to wine64 helped.

**Comment by austin987** [comment]
The documentation could certainly be improved upstream, https://wiki.winehq.org/Building_Wine has some info.

Technically it should work for 64-bit only applications, but many/most 64-bit windows applications also have 32-bit components (even in 2023..).
