### ISSUE TITLE
Doubts about DLL overrides.

### ISSUE THREAD

**Issue by BrandowLucas** [Winetricks/winetricks#2062]
I don't know if this is the correct place to ask, but i didn't find any other place but here, so here goes my question.

When i try to install a trading application (profitchart) it gets really weird with the texts, the workaround is by using winetricks -q riched20, so far so good, but if i try to manually override the DLL on winecfg to native (riched20, native then builtin), the application continues to be glitchy (only fixes it if i override/install the riched20 using winetricks), and I also notices it installs msls31, which i also tried to override on winecfg to native and still didn't work. Does winetricks use a custom DLL than the manual override?

Another case that i found was when i tried to install Resident Evil 4 HD Project, and i had to pass "winetricks -q dinput8" to fix the resolution properly, but then it broke my mouse moviment (i could't move the aim), some weeks later i found out that by manually overriding the dinput8 as native on winecfg fixed both my resolution and the stuck aim.

My question is, does winetricks uses a custom DLL when using it? Or it install something else that might fixes/break certain applications? Please someone kills this doubt that i have because i'm a recent linux user trying to understand what is happening under the hood. Again, sorry if this is the wrong place to ask, thanks in advance.

**Comment by austin987** [comment]
'native' generally means 'from Windows', whereas 'builtin' means 'from Wine'.

When you install riched20 from winetricks, winetricks gets the dll from Microsoft, puts it in the appropriate place in your WINEPREFIX, and sets the override in the registry so that Wine knows to use it.

It's not a 'custom' dll, per se, it's a real dll that comes from Microsoft.

Setting 'native' in winecfg without providing the dll itself won't change any behavior, as Wine doesn't ship Microsoft binaries.
