### ISSUE TITLE
cabextract 1. Aborting error in guix

### ISSUE THREAD

**Issue by Noir16** [Winetricks/winetricks#2096]
Note: command cabextroact -q --directory=/home/{username}/.wine/dosdevices/c:/windows/{system32 or syswow64} /home/{mashiro}/.cache/winetroicks/cmd/{Install exe file name}.exe returned status 1. Aborting.

This issue occurs regardless of whether a user is using the 64 version or not.
It looks like the issue is mainly with Proton, but I don't use it and have a general wine installation.

cabextract version is 1.9.1.

**Comment by austin987** [comment]
Hi @Noir16,

There's not much info here to provide any help. In particular:
* what winetricks version
* the _actual_ terminal output
* wine version
* what command you ran to reproduce this

If the issue is with proton, and particularly with cabextract 1.9.1, the issue may be symlinked files under ~/.wine/drive_c/windows.

Aside from providing the above information, I'd suggest testing with a newer cabextract, if possible.

**Comment by Noir16** [comment]
- what winetricks version
20230212

- the actual terminal output
It's too long and some of it is truncated, which doesn't help me solve the problem.
However, in the terminal, it did seem to give me a DNS connection failure message for the file download link.

- wine version
8.0

- what command you ran to reproduce this
cmd ex) sh winetricks dotnet35


I've given up on guix for now (Because there is an issue with the package build or permissions.), so I'll close the issue for now.
