### ISSUE TITLE
URL is broken for VCRun2019

### ISSUE THREAD

**Issue by The10axe** [Winetricks/winetricks#2141]
So I was attempting to install Star Citizen through Lutris, and it seems it can't download from a file, after little investigation, I figured out that the URL it attempts to download from is broken, indeed it tries to download from:

https://web.archive.org/web/2000/https://web.archive.org/web/20210415064013/https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe

instead of

https://web.archive.org/web/20210415064013/https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe

For some reason, there are bits of another url in front of the actual working url

**Comment by Chiitoo** [comment]
The broken one probably did work before, and the archive does say:

"This page is not available on the web
because of server error"

No idea how permanent of an issue that might be...

**Comment by The10axe** [comment]
The second one works tho, and first one seems like a 404 error in disguise. I hope it will be fixed then. Either by updating the source or by the url going back up.

**Comment by Chiitoo** [comment]
What is your 'winetricks --version'?

I can't re-produce this right now, but it's possible that you are hitting a code-path that I do not due to the recent issues with the web archive.

It seems to be very unreliable at least for some users currently.

As far as I can tell, the 'https://web.archive.org/web/2000/' comes from line 1612 [1] on current master, in 'w_download_to()'.

This probably shouldn't happen for URLs that are already going to the archive, though I'm not entirely sure.

1. https://github.com/Winetricks/winetricks/blob/master/src/winetricks#L1612
