### ISSUE TITLE
dotnet48 still checked after uninstalling

### ISSUE THREAD

**Issue by VanHoevenTR** [Winetricks/winetricks#2158]
There is a minor bug. After I uninstalled NET 4.8 via uninstaller GUI, only "dotnet40" in the "Install a Windows DLL or component" options were unchecked, but the "dotnet48" still checked. Unchecking it manually and clicking OK does nothing, it still gets checked when I open the options again. So there is no way to install it again via GUI

**Comment by austin987** [comment]
That's by design; the 'installed' check is simply looking at what's in $WINEPREFIX/winetricks.log. The .Net installer doesn't know about that file and so it doesn't get updated.

You can manually edit that file to remove the entry, or use --force. That may or may not work; given how hacky the .Net setup stuff is, there's a decent chance that a second install in the same prefix may not work correctly.

**Comment by mirh** [comment]
Fun fact: the uninstaller won't work if the prefix Windows version is set to W10+.
