### ISSUE TITLE
Installation UWP/WINRT runtime with winetricks to support install *.appx package.

### ISSUE THREAD

**Issue by chiddekel** [Winetricks/winetricks#2225]
Add support for *.appx ( Windows Store) app installation package by adding option to install UWP/WINrT runtime
 packages.
 This will solve for example this issue:
 https://askubuntu.com/questions/991858/is-it-possible-to-run-windows-10-uwp-apps-on-ubuntu/1356602#1356602

**Comment by austin987** [comment]
A) That looks incredibly hacky (and as the post points out, may not work for all apps).
B) I think this is outside the scope of winetricks.

**Comment by Weather-OS** [comment]
We can’t use Windows libraries to bring WinRT support in wine even though in theory we could. This is because they rely way too much on other internal Windows libraries and undocumented internal functionality. 
What we need to do is reimplement basically everything there is to WinRT from scratch within wine.

**Comment by chiddekel** [comment]
I found my comment on this topic - i found how to bringing store and runtimes.

**Comment by chiddekel** [comment]
"In theory, if you use Winget/Chocolatey and PowerShell, then UWP/STORE app can work on wine.

Then that we can install runtimes/developer's SDK/library for APPX, MSIXBUNDEL, UWP etc. install by PowerShell.
If error occurs, just resolve errors by [additional install dependency/coding].

If all will work, then add script to Winetricks. Less code to do more ;-) thanks to runtimes/library dependence and Winget/Chocolatey installer ( and lite bit of coding skills )"

**Comment by chiddekel** [comment]
Can you be more specific about it - technically 🗣️ speaking. When you install PowerShell and Winget/chocolate on wine when adding runtimes of windows Store... There will be error running that with specific code of errors - so we can error driving development occurs to start UWP migration on wine.

**Comment by Weather-OS** [comment]
> Can you be more specific about it - technically 🗣️ speaking. When you install PowerShell and Winget/chocolate on wine when adding runtimes of windows Store... There will be error running that with specific code of errors - so we can error driving development occurs to start UWP migration on wine.

Winget relies on WinRT libraries. Windows store runtimes rely on WinRT libraries. Chocolatey relies on Windows store runtimes.
UWP is extremely complicated. However, since it’s COM, again, it is theoretically possible to run full fledged UWP apps on Wine. 

What I’m trying to say is that no matter what we do we still need to implement WinRT libraries in Wine from scratch.

**Comment by chiddekel** [comment]
Try to install on developer machine chocolate/winget on wine set as win 10 and start install library's and runtimes and  then output error log? So we start development of missing code.
