### ISSUE TITLE
xna40 install fails with "DXSetup.exe: Unable to find a version of the runtime to run this application"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Winetricks/winetricks#318]
```
winetricks xna40 is probably missing a prerequisite.

This was mentioned in
http://bugs.winehq.org/show_bug.cgi?id=30718
and is still true today.
```

Original issue reported on code.google.com by `daniel.r...@gmail.com` on 17 Jun 2013 at 2:12

**Comment by Aeva** [comment]
I am running into this problem while attempting to install xna40 through wine tricks.  I would b glad to provide any further information that might help this get fixed, but I do not know what would be useful to provide.

**Comment by austin987** [comment]
Thanks for the reminder. I took a look last night, issue is that it needs .Net 4.5, not 4.0. There are still some issues in log files, I don't know if they are a problem or not for any application needing xna40 though.

Fixed by https://github.com/Winetricks/winetricks/commit/60e9fe389323dd3d9c3788e9ffc87e6888988dd8
