### ISSUE TITLE
winetricks fails to find existing prefix

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Winetricks/winetricks#429]
```
What steps will reproduce the problem?
1. install ubuntu, upgrade to 14.04 LTS (and subsequent updates)
2. install wine, install configure wine, install winetricks, install q4wine
3. run winetricks, "select the default wine prefix" -- because there is no 
"choose prefix" or "browse for prefix", etc.
4. winetricks assigns /home/*user*/.wine as prefix, no edit, no manual entry, 
etc., this does not create a new folder nor link to existing folder (by alias?)

What is the expected output? What do you see instead?
The correct wine prefix from initial wine install -- /home/.wine; a 
non-existant folder string

What version of the product are you using? On what operating system?
not found; 14.04 LTS

Please provide any additional information below.
basic set up fails to find .wine folder, winetricks "menu" loops with no 
resolution


```

Original issue reported on code.google.com by `tbirdman...@gmail.com` on 13 Jun 2014 at 11:42

**Comment by skry** [comment]
I'm having similar problem in Arch, probably related. 

Prefix is OK when changing settings on a clean wine prefix:
$ winetricks prefix=Skyrim ddr=opengl multisampling=enabled psm=enabled vd=off videomemorysize=2048 vsm=hardware win7

Prefix is not OK when trying to install Steam:
$ winetricks prefix=Skyrim steam
Executing w_do_call steam
steam already installed, skipping

There is no Steam installed in that specified prefix. However, Steam is installed in other prefix named 'steam' at ~/.local/share/wineprefixes/steam instead of prefix 'Skyrim'.

Trying to force the install with 
$ winetricks --force prefix=Skyrim steam
will install Steam to prefix 'steam' instead of prefix 'Skyrim'

$WINEPREFIX is empty, and setting it to match the full path to prefix 'Skyrim' does not change behavior in any way.

Looking at verbose output,  WINEPREFIX is what it should be until this happens:
+ case "$OS" in
+ case "$category"-"$WINETRICKS_OPT_SHAREDPREFIX" in
+ winetricks_set_wineprefix steam

**Comment by austin987** [comment]
You need to use --no-isolate when installing steam for it to respect
$WINEPREFIX, see issue 494.

On Sat, May 2, 2015 at 8:44 AM, Joni Lapilainen <notifications@github.com>
wrote:

> I'm having similar problem in Arch, probably related.
>
> Prefix is OK when changing settings on a clean wine prefix:
> $ winetricks prefix=Skyrim ddr=opengl multisampling=enabled psm=enabled
> vd=off videomemorysize=2048 vsm=hardware win7
>
> Prefix is not OK when trying to install Steam:
> $ winetricks prefix=Skyrim steam
> Executing w_do_call steam
> steam already installed, skipping
>
> There is no Steam installed in that specified prefix. However, Steam is
> installed in other prefix named 'steam' at
> ~/.local/share/wineprefixes/steam instead of prefix 'Skyrim'.
>
> Trying to force the install with
> $ winetricks --force prefix=Skyrim steam
> will install Steam to prefix 'steam' instead of prefix 'Skyrim'
>
> $WINEPREFIX is empty, and setting it to match the full path to prefix
> 'Skyrim' does not change behavior in any way.
>
> Looking at verbose output, WINEPREFIX is what it should be until this
> happens:
>
>    - case "$OS" in
>    - case "$category"-"$WINETRICKS_OPT_SHAREDPREFIX" in
>    - winetricks_set_wineprefix steam
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Winetricks/winetricks/issues/429#issuecomment-98360585>
> .
>



-- 
-Austin

**Comment by skry** [comment]
Thanks. I eventually managed to figure it out myself and deleted my comment already.
