### ISSUE TITLE
Retry on missing cabextract

### ISSUE THREAD

**Issue by edwin-v** [Winetricks/winetricks#687]
I would very much like there to be a retry option when cabextract is missing. This error occurs somewhere late in the installation of dotnet45 and can be fixed on the fly. Instead it exits and you have to delete the prefix and start all over again.

**Comment by austin987** [comment]
Retrying is a bit complicated. There have been similar workarounds in the past, where we check if the tool is around at the start before failing at the end.

This is fixed by https://github.com/Winetricks/winetricks/commit/9774ee2bc63ea778c1e0ce1459eeccabfe74d5e7

There may be other similar issues in other verbs, I didn't audit them all.
