### ISSUE TITLE
Weird symbols displayed in terminal after running winetricks --self-update

### ISSUE THREAD

**Issue by slyscorpion** [Winetricks/winetricks#689]
Current winetricks version: 

winetricks 20161012 - sha1sum: 9bc8c69598f84711717a2736e80db950a3e22917

After running "sudo winetricks --self-update" and then simply "winetricks" after updating I receive what you see below: 

`You are running winetricks-20161012, latest upstream is winetricks-32043404���R�    !
`
Not sure if this is something on my end or what so if it's user error, please let me know...

**Comment by austin987** [comment]
On Oct 28, 2016 7:23 PM, "slyscorpion" <notifications@github.com> wrote:
>
> Current winetricks version:
>
> winetricks 20161012 - sha1sum: 9bc8c69598f84711717a2736e80db950a3e22917
>
> After running "winetricks --self-update" and then simply "winetricks" I
receive what you see below:
>
> You are running winetricks-20161012, latest upstream is
winetricks-��32043404����R� !
>
> Not sure if this is something on my end or what so if it's user error,
please let me know...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

No, it's a bug I recently introduced. You can ignore it for now. I'm
treating the fix before pushing.

It doesn't affect aria2c, which is why I didn't notice when I added the
check..

**Comment by slyscorpion** [comment]
Thanks for the reply :) 

By the way, how come winetricks doesn't appear to recognize my version even though I just did a --self-update? Asking because of this: 

`winetricks
Using winetricks 20161012 - sha1sum: 9bc8c69598f84711717a2736e80db950a3e22917 with wine-1.9.21-143-gb22aa57
Executing cd /tmp/winetricks.PlK3MpGg
Downloading https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST to /tmp/winetricks.PlK3MpGg
--2016-10-29 02:17:37--  https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.12.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.12.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 29 [text/plain]
Saving to: ‘LATEST’
`
and then

`You should update using your distribution's package manager, --self-update, or manually.`

**Comment by austin987** [comment]
On Oct 28, 2016 7:33 PM, "slyscorpion" <notifications@github.com> wrote:
>
> Thanks for the reply :)
>
> By the way, how come winetricks doesn't appear to recognize my version
even though I just did a --self-update? Asking because of this:
>
> winetricks
> Using winetricks 20161012 - sha1sum:
9bc8c69598f84711717a2736e80db950a3e22917 with wine-1.9.21-143-gb22aa57
> Executing cd /tmp/winetricks.PlK3MpGg
> Downloading
https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST
to /tmp/winetricks.PlK3MpGg
> --2016-10-29 02:17:37--
https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)...
151.101.12.133
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.12.133|:443...
connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 29 [text/plain]
> Saving to: ‘LATEST’
>
> and then
>
> You should update using your distribution's package manager,
--self-update, or manually.
>
> —
> You are receiving this because you commented.
>
> Reply to this email directly, view it on GitHub, or mute the thread.

The update check fails because of the original bug, so the comparison
fails. You'll always be told to update if using wget (and maybe curl,
didn't test). Ignore the update check for now, until this bug is fixed.

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/4f39ff46f088c63fcaf72ed1234cea08a71abe4f

**Comment by slyscorpion** [comment]
Confirmed, thank you!
