### ISSUE TITLE
Downloading from web.archive.org is aggressive when installing winhttp

### ISSUE THREAD

**Issue by kenorb** [Winetricks/winetricks#690]
In case when web.archive.org is not accessible, retries and connection time outs takes over 1h by connecting over and over again. This is due the recent issue where `web.archive.org` is blocked for some reason from Travis CI builds.

This happening when installing `winhttp`, e.g. `winetricks winhttp`.

Or by using the recent winetricks:

```
sh -s winhttp < <(wget -qO- https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks)
```

Here is demonstration at this [Travis CI build](https://travis-ci.org/EA31337/FX-MT-VM/jobs/171612349#L2337).

```
--2016-10-29 16:48:59--  (try: 2)  https://web.archive.org/web/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE
Connecting to web.archive.org (web.archive.org)|207.241.225.186|:443... failed: Connection timed out.
Retrying.
--2016-10-29 16:51:09--  (try: 3)  https://web.archive.org/web/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE
Connecting to web.archive.org (web.archive.org)|207.241.225.186|:443... failed: Connection timed out.
Retrying.
...
--2016-10-29 17:29:34--  (try:20)  https://web.archive.org/web/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE
Connecting to web.archive.org (web.archive.org)|207.241.225.186|:443... 
```

Each time out takes over 2 minutes, 20 retries gives 40 minutes. Having 7 test builds, the CI tests are stuck for over 4h in overall per each commit.

Shouldn't winetricks have some limit and try to download only 3 or 5 times? Or the timeout value should be smaller (like 10-30 seconds) and fail after that?

**Comment by austin987** [comment]
On Oct 29, 2016 4:37 PM, "Rafal" <notifications@github.com> wrote:
>
> In case when web.archive.org is not accessible, retries and connection
time outs takes over 1h by connecting over and over again. This is due the
recent issue where web.archive.org is blocked for some reason from Travis
CI builds.

Out of curiosity, what project is this for?

> This happening when installing winhttp, e.g. winetricks winhttp.
>
> Or by using the recent winetricks:
>
> sh -s winhttp < <(wget -qO-
https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks)

>
> Here is demonstration at this Travis CI build.
>
> --2016-10-29 16:48:59-- (try: 2)
https://web.archive.org/web/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE
Connecting to web.archive.org (web.archive.org)|207.241.225.186|:443...
failed: Connection timed out. Retrying. --2016-10-29 16:51:09-- (try: 3)
https://web.archive.org/web/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE
Connecting to web.archive.org (web.archive.org)|207.241.225.186|:443...
failed: Connection timed out. Retrying. ... --2016-10-29 17:29:34--
(try:20)
https://web.archive.org/web/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE
Connecting to web.archive.org (web.archive.org)|207.241.225.186|:443...
>
> Each time out takes over 2 minutes, 20 retries gives 40 minutes. Having 7
test builds, the CI tests are stuck for over 4h in overall per each commit.
>
> Shouldn't winetricks have some limit and try to download only 3 or 5
times? Or the timeout value should be smaller (like 10-30 seconds) and fail
after that?

We certainly could. A proposed patch would be welcome. Otherwise I'll look
next week probably.

**Comment by kenorb** [comment]
The purpose of the project is to install mt4 platform headlessly (which was added recently) via winetricks in order to run some headless tests of the financial algorithms. This most likely requires `winhttp` within [this script](https://github.com/EA31337/FX-MT-VM/blob/d5601a915c60712564a89a229afda624d917b075/scripts/install_mt4.sh#L13) for SSL web access which requires installation of SP4 which fails.

**Comment by austin987** [comment]
Here you go: https://github.com/Winetricks/winetricks/commit/aed81bb7d0a8f2d423f7402d38900f561160283e

same for all downloaders, 15 seconds / 3 retries
