### ISSUE TITLE
winetricks vcrun2005: install completed, but installed file mfc80.dll

### ISSUE THREAD

**Issue by samrocketman** [Winetricks/winetricks#692]
# Problem

Trying to install all of the vcrun versions into my wine prefix.  Specifically, I would like to install vcrun6sp6, vcrun2003, vcrun2005, vcrun2008, vcrun2010, vcrun2012, and vcrun2013.

When I run `winetricks vcrun2005` the error I see:

```
$ winetricks vcrun2005
Using winetricks 20161012 - sha1sum: 142a40eb2d8d829cbea2cb18c86df6b66dcde45a with wine-1.9.22
Executing cd /tmp/winetricks.qaCweyZz
Downloading https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST to /tmp/winetricks.qaCweyZz
--2016-11-06 08:06:34--  https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.52.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.52.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9 [text/plain]
Saving to: ‘LATEST’

LATEST                                  100%[============================================================================>]       9  --.-KB/s    in 0s      

2016-11-06 08:06:35 (2.96 MB/s) - ‘LATEST’ saved [9/9]

Executing cd /home/sam/usr/src/winetricks
Executing w_do_call vcrun2005
Executing load_vcrun2005 
Executing cd /home/sam/.cache/winetricks/vcrun2005
Using native,builtin override for following DLLs: atl80 msvcm80 msvcp80 msvcr80 vcomp
Executing winetricks_early_wine regedit C:\windows\Temp\_vcrun2005\override-dll.reg
Executing wine vcredist_x86.EXE
fixme:advapi:DecryptFileA ("C:\\users\\sam\\Temp\\IXP000.TMP\\", 00000000): stub
fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
err:msi:msi_install_assembly Failed to install assembly L"C:\\users\\sam\\Temp\\msi1.tmp\\x86_Microsoft.VC80.ATL_1fc8b3b9a1e18e3b_8.0.50727.6195_x-ww_a4c618fa.manifest" (0x80004001)
err:msi:ACTION_InstallFiles Failed to install assembly
err:msi:ITERATE_Actions Execution halted, action L"InstallFiles" returned 1603
err:msi:ITERATE_Actions Execution halted, action L"ExecuteAction" returned 1603
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
------------------------------------------------------
vcrun2005 install completed, but installed file /home/sam/.wine/dosdevices/c:/windows/winsxs/x86_microsoft.vc80.mfc_1fc8b3b9a1e18e3b_8.0.50727.6195_none_deadbeef/mfc80.dll not found
------------------------------------------------------
```

# Versions

Here's my versions:
```
$ lsb_release -d
Description:    Ubuntu 16.04.1 LTS
$ type -p winetricks
/home/sam/usr/bin/winetricks
$ winetricks -V
20161012 - sha1sum: 142a40eb2d8d829cbea2cb18c86df6b66dcde45a
```

Installed from master branch @ d1c3d3f53491a4534368ba06a3f5ecf005a32936.

I'm not sure what sha1sum refers to because I definitely checked out from source the latest master at the time of reporting this issue.  Edited PREFIX in `Makefile` to point to `/home/sam/usr`.  I executed `make install`.

# Other info

I have libxml2 package installed on my system.

```
$ dpkg -l | grep libxml2
ii  libxml-libxml-perl                              2.0123+dfsg-1build1                           amd64        Perl interface to the libxml2 library
ii  libxml2:amd64                                   2.9.3+dfsg1-1ubuntu0.1                        amd64        GNOME XML library
ii  libxml2:i386                                    2.9.3+dfsg1-1ubuntu0.1                        i386         GNOME XML library
ii  libxml2-dev:amd64                               2.9.3+dfsg1-1ubuntu0.1                        amd64        Development files for the GNOME XML library
ii  libxml2-utils                                   2.9.3+dfsg1-1ubuntu0.1                        amd64        XML utilities
ii  python-lxml                                     3.5.0-1build1                                 amd64        pythonic binding for the libxml2 and libxslt libraries
ii  python3-lxml                                    3.5.0-1build1                                 amd64        pythonic binding for the libxml2 and libxslt libraries
```

**Comment by qwertychouskie** [comment]
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.



Run winetricks msxml3 msxml4 msxml6 .

On 11/06/2016 08:08 AM, Sam Gleske wrote:
Problem

Trying to install all of the vcrun versions into my wine prefix. Specifically, I would like to install vcrun6sp6, vcrun2003, vcrun2005, vcrun2008, vcrun2010, vcrun2012, and vcrun2013.

When I run `winetricks the error I see:

$ winetricks vcrun2005
Using winetricks 20161012 - sha1sum: 142a40eb2d8d829cbea2cb18c86df6b66dcde45a with wine-1.9.22
Executing cd /tmp/winetricks.qaCweyZz
Downloading https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST to /tmp/winetricks.qaCweyZz
--2016-11-06 08:06:34--  https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.52.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.52.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9 [text/plain]
Saving to: ‘LATEST’

LATEST                                  100%[============================================================================>]       9  --.-KB/s    in 0s

2016-11-06 08:06:35 (2.96 MB/s) - ‘LATEST’ saved [9/9]

Executing cd /home/sam/usr/src/winetricks
Executing w_do_call vcrun2005
Executing load_vcrun2005
Executing cd /home/sam/.cache/winetricks/vcrun2005
Using native,builtin override for following DLLs: atl80 msvcm80 msvcp80 msvcr80 vcomp
Executing winetricks_early_wine regedit C:\windows\Temp\_vcrun2005\override-dll.reg
Executing wine vcredist_x86.EXE
fixme:advapi:DecryptFileA ("C:\\users\\sam\\Temp\\IXP000.TMP\\", 00000000): stub
fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
err:msi:msi_install_assembly Failed to install assembly L"C:\\users\\sam\\Temp\\msi1.tmp\\x86_Microsoft.VC80.ATL_1fc8b3b9a1e18e3b_8.0.50727.6195_x-ww_a4c618fa.manifest" (0x80004001)
err:msi:ACTION_InstallFiles Failed to install assembly
err:msi:ITERATE_Actions Execution halted, action L"InstallFiles" returned 1603
err:msi:ITERATE_Actions Execution halted, action L"ExecuteAction" returned 1603
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
This program tried to use a DOMDocument object, but
libxml2 support was not present at compile time.
fixme:ole:CoCreateInstanceEx no instance created for interface {2933bf81-7b36-11d2-b20e-00c04f983e60} of class {f6d90f11-9c73-11d3-b32e-00c04f990bb4}, hres is 0x80004001
------------------------------------------------------
vcrun2005 install completed, but installed file /home/sam/.wine/dosdevices/c:/windows/winsxs/x86_microsoft.vc80.mfc_1fc8b3b9a1e18e3b_8.0.50727.6195_none_deadbeef/mfc80.dll not found
------------------------------------------------------


Versions

Here's my versions:

$ lsb_release -d
Description:    Ubuntu 16.04.1 LTS
$ type -p winetricks
/home/sam/usr/bin/winetricks
$ winetricks -V
20161012 - sha1sum: 142a40eb2d8d829cbea2cb18c86df6b66dcde45a


Installed from master branch @ d1c3d3f<https://github.com/Winetricks/winetricks/commit/d1c3d3f53491a4534368ba06a3f5ecf005a32936>.

I'm not sure what sha1sum refers to because I definitely checked out from source the latest master at the time of reporting this issue. Edited PREFIX in Makefile to point to /home/sam/usr. I executed make install.

**Comment by austin987** [comment]
On Nov 6, 2016 7:13 PM, "QwertyChouskie" <notifications@github.com> wrote:
>
> This program tried to use a DOMDocument object, but
> libxml2 support was not present at compile time.
>
>
>
> Run winetricks msxml3 msxml4 msxml6 .

The proper fix is to rebuild wine with libxml2 support.

**Comment by samrocketman** [comment]
> The proper fix is to rebuild wine with libxml2 support.

I've rebuilt wine more than once.  I'm going to try a few more things.  Here's how I've built it.  https://github.com/samrocketman/buildwine

**Comment by samrocketman** [comment]
Recompiled wine after [installing `libxml2:i386`](https://github.com/samrocketman/buildwine/blob/master/dependencies.sh) package and the error went away.  After that I was able to install every version of vcrun except for `vcrun2012` and `vcrun2013`.

I still can't seem to get those two to install.  Here's the errors I see.

```
$ winetricks vcrun2012
Using winetricks 20161012 - sha1sum: 142a40eb2d8d829cbea2cb18c86df6b66dcde45a with wine-1.9.22-72-gf7187ec
Executing cd /tmp/winetricks.jTZ6iV3z
Downloading https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST to /tmp/winetricks.jTZ6iV3z
--2016-11-06 23:55:13--  https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.52.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.52.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9 [text/plain]
Saving to: ‘LATEST’

LATEST                                  100%[============================================================================>]       9  --.-KB/s    in 0s      

2016-11-06 23:55:13 (3.78 MB/s) - ‘LATEST’ saved [9/9]

Executing cd /home/sam/git/github/buildwine
Executing w_do_call vcrun2012
Executing load_vcrun2012 
Using native,builtin override for following DLLs: atl110 msvcp110 msvcr110 vcomp110
Executing winetricks_early_wine regedit C:\windows\Temp\_vcrun2012\override-dll.reg
Executing cd /home/sam/.cache/winetricks/vcrun2012
Executing wine vcredist_x86.exe
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040111
err:ole:CoGetClassObject no class object {f5078f1b-c551-11d3-89b9-0000f81fe221} could be created for context 0x1
------------------------------------------------------
Note: command wine vcredist_x86.exe returned status 17.  Aborting.
------------------------------------------------------
```

```
$ winetricks vcrun2013
Using winetricks 20161012 - sha1sum: 142a40eb2d8d829cbea2cb18c86df6b66dcde45a with wine-1.9.22-72-gf7187ec
Executing cd /tmp/winetricks.dRhSbZ2o
Downloading https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST to /tmp/winetricks.dRhSbZ2o
--2016-11-06 23:56:22--  https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.52.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.52.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9 [text/plain]
Saving to: ‘LATEST’

LATEST                                  100%[============================================================================>]       9  --.-KB/s    in 0s      

2016-11-06 23:56:23 (3.56 MB/s) - ‘LATEST’ saved [9/9]

Executing cd /home/sam/git/github/buildwine
Executing w_do_call vcrun2013
Executing load_vcrun2013 
Using native,builtin override for following DLLs: atl120 msvcp120 msvcr120 vcomp120
Executing winetricks_early_wine regedit C:\windows\Temp\_vcrun2013\override-dll.reg
Executing cd /home/sam/.cache/winetricks/vcrun2013
Executing wine vcredist_x86.exe
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040111
err:ole:CoGetClassObject no class object {f5078f1b-c551-11d3-89b9-0000f81fe221} could be created for context 0x1
------------------------------------------------------
Note: command wine vcredist_x86.exe returned status 17.  Aborting.
------------------------------------------------------
```

Thanks for your help so far.

**Comment by austin987** [comment]
You probably want i386 -dev package

**Comment by samrocketman** [comment]
> You probably want i386 -dev package
In my previous comment, I mention I resolved it by installing i386 -dev package.

**Comment by austin987** [comment]
Edits to comments aren't sent as email notifications, fyi.

**Comment by samrocketman** [comment]
> Edits to comments aren't sent as email notifications, fyi.

Good to know.  I'll write follow-up comments rather than editing my last comment.

**Comment by samrocketman** [comment]
Also, you might want to visit GitHub because I've edited prior comments since you posted about the email notifications.

**Comment by austin987** [comment]
Use https://forum.winehq.org/ for help with compiling wine.

**Comment by samrocketman** [comment]
Thanks for your help.
