### ISSUE TITLE
Decouple this sheet of code into modules

### ISSUE THREAD

**Issue by KOLANICH** [Winetricks/winetricks#716]
I was a bit surprised when I saw that winetricks is a large sheet of code written in bash. So I think that you should start reingeneering it:
1 Decompose into framework core and standalone modules using framework.
2 Rewrite it into python 3. Since python3 is present on major distros by default, this should not do much trouble.

**Comment by austin987** [comment]
The single file is intentional, to allow for easy updates. I don't see much benefit to refactoring it at this point, and it would be a significant amount of work. 

A Python rewrite is something I'd like to do, but it's a noob trivial task and I lack time for it, as I already have a demanding day job and other projects that need my attention. 

Anyway, it's LGPL and on github. If you think you can do it better, hit the fork button.
