### ISSUE TITLE
msacm32 winetrick fails with sha256sum mismatch

### ISSUE THREAD

**Issue by gverm** [Winetricks/winetricks#769]

**Comment by austin987** [comment]
Looks like archive.org is having issues. Unfortunately I  haven't seen an alternative source

**Comment by real-or-random** [comment]
Then probably related to #770. As a workaround, it seems that older snapshots (2015) from archive.org are accessible but you have to download them manually to ~/.cache/winetricks.

**Comment by real-or-random** [comment]
> As a workaround, it seems that older snapshots (2015) from archive.org are accessible but you have to download them manually to ~/.cache/winetricks.
And just took me 30 min to figure out that I had to use a fresh wine prefix because winetricks assumed that the installation of riched20 worked and did not install again. (Now looking at --help, calling winetricks with --force should also do the job).

I think that should be a bug in error handling.

**Comment by austin987** [comment]
Then please file a separate bug, with instructions on how to reproduce.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/06a872372cee679237d5a27d5f4bdf40b4d515cd
