### ISSUE TITLE
Some fonts can't install

### ISSUE THREAD

**Issue by 601t** [Winetricks/winetricks#921]
My Environment
Linux Mint 18.3 Xfce
Kernel 4.4.0-109
Wine 3.0-rc5 (Maybe 2.0.4 and 2.21.0)
winetricks 20171222

I tried to install "allfonts", but error message [Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/USERNAME/.wine terminate] show me.
Then, I tried to install all fonts separately.
As a result, I found that I couldn't install "constantia", "corefonts", "droid", and "pptfonts".

My English is rude. Sorry.

**Comment by mihaitodor** [comment]
Interesting... Would it be possible to get a detailed winetricks log? For example, run winetricks -v allfonts > out.log 2>&1 and upload the resulting out.log somewhere. Thanks!

**Comment by alexfornuto** [comment]
I'm getting this error, but it seems to me that sometimes the previous font install is causing the warning. Perhaps a `sleep` in between font installations will help?

**Comment by Kreyren** [comment]
@alexfornuto make a new issue for this and provide system info (using `neofetch -off` for example) list of installed packages (`apt list --installed` for example) and output from terminal after executing winetricks to install expected font

**Comment by austin987** [comment]
While a new bug should be opened, there's no need for package lists or system info. It's almost never useful for winetricks.

From what I gather, the issue is most likely that a process is still running in the prefix, so wineserver never exits, and the next font doesn't install. `wineserver -w` acts like sleep, but that all processes have exited, so registry changes take effect.

**Comment by Kreyren** [comment]
> While a new bug should be opened, there's no need for package lists or system info. It's almost never useful for winetricks.

Useful to me, I prefer talking to the end-user's system instead of the end-user sometimes.. seems to lie less :p

**Comment by alexfornuto** [comment]
Yea I totally _would_, but I've abandoned the attempted config that required those font, and am not sure when I'll be back in wine land.

**Comment by Kreyren** [comment]
> *excuses*

noted

**Comment by alexfornuto** [comment]
Well I provided information that I thought would be helpful. I told you why I wouldn't be providing additional debugging help, instead of just ghosting the thread. I'm trying to be a helpful community member, within the confines of the time I'm willing to spend.

Responses like the one above only condition me and others to _not _ engage.

I will provide the system info requested the next time I'm on the computer in question.

**Comment by Kreyren** [comment]
@alexfornuto well my ethique is that everything is helpful as long as its relevant, but what do you expect me to do exactly?

I can't reproduce the issue,
I nor I don't know how to fix the issue on affected systems nor what is causing this issue which are mandatory for me to investigate

**Comment by austin987** [comment]
@alexfornuto, please don't think that Kreyren represents the project. While a new bug (and log) would be more helpful than a comment on a closed bug, I do appreciate the info / letting me know you were no longer interested.

Anyway, if you see this in the future and care, please open a new issue with the full terminal output. I suspect though that an app was running in the prefix, so watch out for that next time :).

**Comment by alexfornuto** [comment]
:heart: @austin987 I'll do my best to circle back.

FYI the site listed in your GH bio attempts to download instead of opening in both Chrome and FF - I suspect MIME type to blame.
