### ISSUE TITLE
Takes forever to install msie6

### ISSUE THREAD

**Issue by mk-pmb** [Winetricks/winetricks#961]
… because of the huge winxpsp3 download. In the past, `winetricks --unattended ie6` was a matter of minutes. :+1: MSIE6 probably hasn't changed since then, so why do I need SP3 now?

**Comment by austin987** [comment]
That's because ie6 uses pngfilt, which now uses the xp dll instead of the win2k version (since 2017/05).

**Comment by mk-pmb** [comment]
Thanks! I'll try with windows version set to win2k then next time.

**Comment by austin987** [comment]
Fyi that won't make a difference, winetricks doesn't check the running Windows version for what Windows dll to get.

**Comment by mk-pmb** [comment]
Would it help to copy the DLL from my original WinXP into my wineprefix's `system32` dir before I try and install ie6?

**Comment by austin987** [comment]
@mk-pmb, currently no, the dll is unconditionally extracted. In theory it could be made conditional since wine doesn't ship it, so it won't ever exist by default, but if wine adds one, it gets trickier.

Once you've download xpsp3, it will be cached and not downloaded again (unless you're running under different users/vms or something). Many verbs use xpsp3, so it's not a rare requirement.
