### ISSUE TITLE
DXVK and Vkd3d as winetricks packages

### ISSUE THREAD

**Issue by j3ky** [Winetricks/winetricks#999]
I've been wondering,

It would be great `winetricks` being able to install both projects latest binaries as we do with VulkanSD, Steam...

A feature to install/update to their latest binaries would add even more attention to `winetricks` project! 

Thanks!

**Comment by austin987** [comment]
Those are linux binaries / custom wine forks, not win32/64 packages.  That is outside the scope of winetricks.

**Comment by qwertychouskie** [comment]
At least DXVK and VK9 are built as DLLs to be put into the wine prefix, don't know about VKD3D though.

**Comment by austin987** [comment]
I've never used them, so perhaps I'm wrong. Are they not native elf binaries? Or are they win32/64 binaries?

**Comment by qwertychouskie** [comment]
DXVK is distributed as `d3d11.dll` and `dxgi.dll` files with 32-bit and 64-bit versions in the package (https://github.com/doitsujin/dxvk/releases/download/v0.51/dxvk-0.51.tar.gz).  VK9 is also distributed as a `d3d9.dll` and some supporting files (https://github.com/disks86/VK9/releases).  In fact, VK9 is developed primarily on Windows.  Also some people have used DXVK in Windows.

**Comment by austin987** [comment]
I see, thanks for the info.

**Comment by bobwya** [comment]
@austin987

DXVK has frequent releases, with pre-built PE 32-bit and PE+ 64-bit binary dll's. DXVK hooks into Wine / Wine Staging by providing alternative dxgi.dll and d3d11.dll files, that can be enabled using standard Wine DLL overrides. DXVK provides setup shell scripts to do this automatically. Under the hood DXVK leverages Wine-Vulkan to do the system Vulkan calls.

The impact of DXVK on some DX11 titles is nothing short of phenomenal! E.g. Grand Theft Auto V is nearly on parity with native Windows.

**Comment by shmerl** [comment]
This is a good fit for winetricks indeed.

**Comment by bobwya** [comment]
@SveSop 

There's official **Gentoo** package for this now... See: [wine overlay : vkd3d-1.0.ebuild](https://gitweb.gentoo.org/repo/proj/wine.git/plain/app-emulation/vkd3d/vkd3d-1.0.ebuild?id=5cd242b5b356c7bb99b9e4920acb282ce4b6197a)

Though I'm still not sure what you can actually do with a D3D12 translation layer...??
Aren't most **D3D12** games **UWP** applications?

I don't think a **winetricks** verb is useful for this library... It'll probably go in the distribution official repositories - since it **is** the Wine **D3D12** translation layer (there won't be one leveraging OpenGL).

**Comment by mihawk90** [comment]
> Aren't most D3D12 games UWP applications?

nah, there are quite some DX12 games that aren't UWP:
https://en.wikipedia.org/wiki/List_of_games_with_DirectX_12_support

Just a few I know aren't UWP would be Rise of the Tomb Raider, Battlefront I/II, Division, Hitman, Ashes, Deus Ex, BF1, Civ VI. Also Metro Exodus and Battle for Azeroth are probably not going to be UWP.

Then again none of those are DX12 *exclusive*, only support. All the DX12 exclusives on that list are basically XBONE ports.

It'll be some time until we see actual DX12 games that are built on it from the ground up since engines pretty much need to be rewritten for it, and some studios already said they might as well use Vulkan at that point.

**Comment by bobwya** [comment]
I've taken a look at the **VK9** project. Currently it's a bit of an unholy mess to package in **winetricks**. Apart from the 10,000,000 supporting files (wtf??) You can tell the Developer is working on Windows, as he's releasing the binaries in a **zip**-file, with rampant case-sensitivity issues for Wine (e.g. **D3d9.dll** - wtf). I tried firing it up - nothing happened... So I'll have to re-visit this another day...

**Comment by bobwya** [comment]
@austin987 

I'd suggest closing this issue... 

*VK9** distributes pre-built binaries - but the project is a bit of mess compared to **DXVK** (too many helper files required, file case issues, etc.) Never mind that I can't even get the pre-built binaries to do anything anyway...

**DXUP**  has somewhat limited usefulness (IMHO). But I guess a combined **DXUP** + **DXVK** verb could be contemplated in the future (as they are very inter-dependent).

**DXVK** has a **winetricks** verb now.

**Vkd3d** is released as a source tarball in order for downstream Linux distributions to build it, as binary packages (or provide build scripts for it). There is nothing for **winetricks** to do here...

**Comment by qwertychouskie** [comment]
DXUP should probably be a part of the DXVK verb IMO.

**Comment by mihawk90** [comment]
Also, just read this:

https://www.winehq.org/news/2018052501

Does this mean vkd3d will be part of core wine?

**Comment by shmerl** [comment]
Yes, as long as wine is configured to be built with it.

**Comment by mihawk90** [comment]
Meaning that a winetrick for it would be also unnecessary, correct?

**Comment by shmerl** [comment]
Yes.

**Comment by shmerl** [comment]
May be there can be an option to always pull the latest version instead of hardcoding it? It would remove the need to update winetricks all the time.

**Comment by austin987** [comment]
Dxvk would have to provide a staple URL for that

**Comment by shmerl** [comment]
Sure, I can open a ticket about that.

**Comment by austin987** [comment]
Cool, thanks @shmerl. I've added that here:
https://github.com/Winetricks/winetricks/commit/c423a85b3cfda1e6181fc8164b089842964a0794

I'm going to close this. Other/follow up issues should be filed as new bugs.
